### ISSUE TITLE
Payment status "Authorized" won't get updated to "Paid" later on

### ISSUE THREAD

**Issue by airplanemta** [mollie/Shopware6#102]
If a customer pays with e.g. Klarna and the payment reaches the status "Authorized", then the status will correctly be forwarded to Shopware. After a few days though the payment status usually changes from "Authorized" to "Paid" in Mollie, but it won't be forwarded to Shopware.

I checked all of our recent orders in Mollie and in Shopware - while in Mollie they're all marked as paid, in Shopware they're still marked as authorized and never updated.

**Comment by schmitzcarsten** [comment]
@airplanemta thx for reporting this. We will have a check and come back to you

**Comment by boxblinkracer** [comment]
hi there
just did a pull request to fix this issue
https://github.com/mollie/Shopware6/pull/128

**Comment by schmitzcarsten** [comment]
will be part of the next release, planned for next week

**Comment by schmitzcarsten** [comment]
@airplanemta mollie release with fix will be on next Monday. We've got a public holiday yesterday. I had to reschedule the release

**Comment by schmitzcarsten** [comment]
closed, fix released with v1.4.1
