### ISSUE TITLE
Payments with a country, which is tax free, lead to an exception

### ISSUE THREAD

**Issue by henrikvolmer** [mollie/Shopware6#12]
Related to the last comment in Issue #4  the bug is not fixed yet. Therefore the new ticket :)

**Comment by henrikvolmer** [comment]
After the new update 1.0.10 the configuration creates a new exception.

![Bildschirmfoto 2020-05-05 um 15 12 30](https://user-images.githubusercontent.com/25845699/81070159-294f3a80-8ee3-11ea-86b7-6903e550d49a.png)

**Comment by reindernl** [comment]
Can you provide me with the data that is sent to Mollie? Which products are in the order and what are there specifics? Thanks in advance!

**Comment by henrikvolmer** [comment]
OrderData:
![Bildschirmfoto 2020-05-15 um 09 31 58](https://user-images.githubusercontent.com/25845699/82024048-7d9aad00-968f-11ea-9df3-fd522c2b9277.png)

Response:
![Bildschirmfoto 2020-05-15 um 09 32 05](https://user-images.githubusercontent.com/25845699/82024068-83908e00-968f-11ea-9fab-6f1c196d3fc9.png)

**Comment by reindernl** [comment]
Thanks for sharing the extra information. I will have a talk with Mollie regarding the API response. Maybe I'm wrong, but as far as I know, if a product costs 1 euros, including 19% tax, you calculate the tax by: (1 / 119) * 19 = 0.16. Their math is different. And I'm not sure why.

In the subject of this ticket you mention tax free. Is that also an issue here? Should the tax not even be calculated? Or was that a different issue?

**Comment by reindernl** [comment]
A I see it now, the given unit price is a net price. And Mollie calculates the tax over that. Okay, I know where I have to look for solving this problem now. Thanks for your help.

**Comment by reindernl** [comment]
Hi Henrik,

A new version of the plugin is released. There's an added check to see if the order was tax free, look here:
https://github.com/mollie/Shopware6/blob/master/src/Service/OrderService.php#L131

Hopefully this works out for you.

My kind regards,
Reinder.
