### ISSUE TITLE
Maintenance of configurations in several sales channels simultaneously is not possible

### ISSUE THREAD

**Issue by henrikvolmer** [mollie/Shopware6#13]
In Shopware 6 there is the possibility to make plugin configurations for all sales channels at the same time. This is not possible in the current Mollie plugin. 

Shopware 6 saves the column `sales_channel_id` in the table `system_config` as `zero` if configurations are made for all sales channels.

The following line ensures that this is not possible in the Mollie Plugin: 

https://github.com/mollie/Shopware6/blob/69dc695b90ad98a5babb2120f5709a2b048aa9ab/src/Service/SettingsService.php#L80

Please fix the logic accordingly :)

**Comment by reindernl** [comment]
Unfortunately Shopware 6 doesn't fall back to the data on 'all saleschannels' by itself. We created a solution for that in the current release: https://github.com/mollie/Shopware6/blob/master/src/Service/SettingsService.php
