### ISSUE TITLE
the plugin is using an incorrect return / redirect url

### ISSUE THREAD

**Issue by cschwerdt** [mollie/Shopware6#133]
Hi 👋🏻,
shopware has apparently introduced new Transaction URLS in its latest version (6.4). This means that the current Mollie plugin (1.4.1) cannot yet be used for version 6.4.

At the following point in the code:
[https://github.com/mollie/Shopware6/blob/6826ccf40b455ef702f9e4a9ee68796f037adae3/src/Handler/PaymentHandler.php#L225](https://github.com/mollie/Shopware6/blob/6826ccf40b455ef702f9e4a9ee68796f037adae3/src/Handler/PaymentHandler.php#L225)

a different URL than expected is returned when "$transaction-> getReturnUrl ()" is called.
Shopware 6.4 now gives a URL with a JWT token, which means that the maximum number of characters of the Mollie API is exceeded.
`https://<shop-domain.tld>/payment/finalize-transaction?_sw_payment_token=<jwt-token>`

This JWT token contains a return url under the "ful" key.

For a quick fix in one of our projects, I parsed the "jwt token" from the url and decoded it. Then I passed the value in the "ful" key as returnUrl to Mollie. This worked on the quick. However, proper implementation would be desirable.

Unfortunately, i was unable to prepare a generally valid "fix", in terms of time.

I hope I could help!

---

**Original Error Message:**
`Could not create a Mollie Payment Url, error: Could not create Mollie order, error: [2021-05-26T15:15:37+0000] Error executing API call (422: Unprocessable Entity): The redirect URL is too long. It should not be longer than 1023 characters. Field: payment.redirectUrl.`

**Comment by schmitzcarsten** [comment]
@cschwerdt Thx for the report. I will have a look on the issue soon. We never encountered the problem before and did a lot of testing with 6.4. May you tell me some more information? e.g. special configuration in your environment

Thx

**Comment by schmitzcarsten** [comment]
we are working on a fix.

**Comment by boxblinkracer** [comment]
Hi

if this is the error for "return url is too long" then this is the fix
https://github.com/mollie/Shopware6/pull/154/files

all cypress tests seem fine, still its not "officially" tested, but I guess you will immediately see if its working

the solution is to just remove the returnUrl als parameter.
its not used anyway, because its taken from the database (order - custom fields).
so its not making a difference if the parameter exists or not

let me know if it works for you

**Comment by schmitzcarsten** [comment]
fixed with release 1.4.2
