### ISSUE TITLE
Refund through Mollie

### ISSUE THREAD

**Issue by powolnymarcel** [mollie/Shopware6#138]
Hello,

We are unable to refund a single item from an order, after clicking "Refund through Mollie" we get this 500 error:

"The controller for URI "/api/v2/_action/mollie/refund/total" is not callable: Controller "Kiener\MolliePayments\Storefront\Controller\RefundController" does neither exist as service nor as class." 

We are using Shopware "v6.3.4.1 Stable Version"
Mollie Shopware version 1.4.1

Can you help =) ?

**Comment by schmitzcarsten** [comment]
sound like cache problem. empty cache and give it another try. Feature works in all of our test environments. 

But we are refactoring refunds at the moment, there will be changes here in one of the next releases.
