### ISSUE TITLE
Any news regarding packagist integration

### ISSUE THREAD

**Issue by AndreasA** [mollie/Shopware6#143]
It should really be quite simple to add it and would make installations through composer easier.

see old issue: https://github.com/mollie/Shopware6/issues/41

**Comment by boxblinkracer** [comment]
hi. do you mean this one? https://packagist.org/packages/kiener/mollie-payments-plugin

**Comment by AndreasA** [comment]
Hi @boxblinkracer not sure why but for some reason I missed it when searching the last time.

Probably because I was searching for a different vendor name `mollie`. The name `mollie/shopware6-plugin` or similar would probably be better but not sure how much effort such a rename would be and if it is worth the effort.

**Comment by boxblinkracer** [comment]
hi

perfect

that name was set before we started to maintain the plugin. its indeed not a perfect one and we already discussed a change, but phu...kinda risky :)
would still be great to have it changed and branded as "mollie"
