### ISSUE TITLE
Could not create order, redirectUrl is too long

### ISSUE THREAD

**Issue by niklaswolf** [mollie/Shopware6#148]
I get the following error message when trying to create an order with Mollie.

> Could not create Mollie order, error: [2021-06-17T07:48:46+0000] Error executing API call (422: Unprocessable Entity): The redirect URL is too long. It should not be longer than 1023 characters. Field: payment.redirectUrl. Documentation: https://docs.mollie.com/reference/v2/orders-api/create-order

Our host has 24 characters, so the complete returnUrl has 1042 characters, which is too long.

Here is the complete URL, I replaced our host with #HOST# (2 times)
> https://#HOST#/mollie/payment/3e913104cc8344d78a740d6ae9c296bd?returnUrl=https%253A%252F%252F#HOST#%252Fpayment%252Ffinalize-transaction%253F_sw_payment_token%253DeyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJqdGkiOiJiZTEwOWJhMWUwZDQ0OTlmYjIwOTUxYTM5YWUzNjgxNCIsImlhdCI6MTYyMzkxNjEyNiwibmJmIjoxNjIzOTE2MTI2LCJleHAiOjE2MjM5MTc5MjYsInN1YiI6IjNlOTEzMTA0Y2M4MzQ0ZDc4YTc0MGQ2YWU5YzI5NmJkIiwicG1pIjoiZTgyZGY3ODg4ZDFjNGFiMjk4YTRmNzY5YjI2MTI5YTkiLCJmdWwiOiJodHRwOi8vbXJhZWRlcjI0LnRlc3Qvb3JkZXItc3VjY2Vzcz9vcmRlcklkPTM0MGRhYThkMjAyMjRhNjBhMzk0ZjZhZmRhMTk3ZjI2IiwiZXVsIjoiaHR0cDovL21yYWVkZXIyNC50ZXN0L3BheW1lbnQtZmFpbHVyZT9vcmRlcklkPTM0MGRhYThkMjAyMjRhNjBhMzk0ZjZhZmRhMTk3ZjI2In0.HrLj-UdEfY6F5w-Wh-5Ar4ZPU6F7rMl14A1ECAAvlkpR0oIZPT3mc2zVs7Sby8MBGkweC_aT1GYkgNjTtaMjK8T2F5fPNAEwozZA3FyX7FO9MNSwK3bYWdIR_c4_w-7Vi4OZEnXmwd7PJ4kz6Gcj5HsWRZsADCEiFBXSBE85H2M7_eER4Dwqic1Bvu5exwByIXE5Tib0g3SX4evY3gBd2GJpklTNVdLfWBADZioNQf1n38ZBumHtGCpyVLqm9qCNFpa9pCyzgV7NmSSni5Dq0dZdYJhxmydcOVi3Fcjc6oUDpxyq27_0QYTXyvY-XR00cGT1Nk0YU2J-CEM504tSnQ

Plugin Version 1.4.1
Shopware 6.4.1.0

**Comment by schmitzcarsten** [comment]
We are working on a fix. Hopefully it is ready for next release.

**Comment by niklaswolf** [comment]
@schmitzcarsten when will this be available? This is a critical bug for us, as payments are simply not working!

**Comment by boxblinkracer** [comment]
Hi Niklas

its already fixed but in a pending PR
but if you are a developer, you could change it using this PR
https://github.com/mollie/Shopware6/pull/154

all cypress tests seem fine, still its not "officially" tested, but I guess you will immediately see if its working

the solution is to just remove the returnUrl als parameter.
its not used anyway, because its taken from the database (order - custom fields).
so its not making a difference if the parameter exists or not

let me know if it helps

**Comment by niklaswolf** [comment]
@boxblinkracer  thanks for the quick reply, we'll have a look into it :)

**Comment by schmitzcarsten** [comment]
fixed with release 1.4.2

**Comment by niklaswolf** [comment]
Thanks for fixing, it now works again :)
