### ISSUE TITLE
Creditcard components: Mollie field validation texts are always loaded in English

### ISSUE THREAD

**Issue by dl-mbegerau** [mollie/Shopware6#17]
### Environment

OS: Ubuntu 18.04
Apache: 2.4.29
PHP: 7.3.17
MySQL: 5.7.30
Shopware: 6.1.5 (fresh installation from production repository)
Mollie: 1.0.10
Other Plugins: Shopware 6 Demo data (1.0.5)

### Problem
The field validation errors which are loaded from Mollie via iFrame always use the locale en_US

_Image: German components with English errors_
![de_with_english_errors](https://user-images.githubusercontent.com/57012534/81895063-f9ed9d00-9576-11ea-8893-8bf3eef4756b.png)

### Detected causes
custom/plugins/MolliePayments/src/Resources/assets/js/components.creditcard.js, lines 14-18

```
14        // Initialize Mollie Components instance
15        const mollie = Mollie('[mollie_profile_id]', {
16            locale: '[mollie_locale]',
17            testmode: [mollie_testmode]
18        });
```

The "locale" property should be set to the locale of the current storefront.

custom/plugins/MolliePayments/src/Storefront/Controller/ComponentsController.php, lines 111-113

```
111        $javascript = str_replace('[mollie_profile_id]', $mollieProfileId, $javascript);
112        $javascript = str_replace('[mollie_locale]', $this->getLocale($context), $javascript);
113        $javascript = str_replace('[mollie_testmode]', $this->config::testMode() === true ? 'true' : 'false', $javascript);
```

$this->getLocale($context) always results in "en-US".

custom/plugins/MolliePayments/src/Storefront/Controller/ComponentsController.php, lines 182-185

```
182        /**
183         * Get the language object from the sales channel context.
184         */
185        $language = $context->getSalesChannel()->getLanguage();
```

$context->getSalesChannel()->getLanguage() is null. Only the languageId is set in context not the language object.

custom/plugins/MolliePayments/src/Storefront/Controller/ComponentsController.php, lines 196-201

```
196        /**
197         * Check if the shop locale is available.
198         */
199        if ($locale === '' || !in_array($locale, $availableLocales, true)) {
200            $locale = 'en_US';
201        }
```

The locales in the $availableLocales array use underscore like "en_US" while the Shopware locale uses hyphen like "en-US", so the in_array function will always return false.

### Solution suggestion
1. Add the language repository as argument to the controller service
2. Search for the language entity (add locale as association in the criteria)
3. Replace hyphen with underscore in the Shopware locale code.
4. Set the language object in the $context or pass the found language/locale directly to $this->getLocale()

Something like this at the beginning of the componentsJs function:
```
if (!$context->getSalesChannel()->getLanguage() || !$context->getSalesChannel()->getLanguage()->getLocale()) {
	$criteria = new Criteria([$context->getSalesChannel()->getLanguageId()]);
	$criteria->addAssociation('locale');

	/** @var LanguageEntity $lang */
	$lang = $this->languageRepository->search($criteria, $context->getContext())->first();
	$code = $lang ? $lang->getLocale()->getCode() : '';
} else {
	$code = $context->getSalesChannel()->getLanguage()->getLocale()->getCode();
}

$code = str_replace('-', '_', $code);
...
```

Even with this fix the "One or more fields are invalid." still remains in English. We don't know where this comes from or how to fix this.

**Comment by reindernl** [comment]
I will get back to you early next week regarding this issue. We couldn't manage to fix it in the version released today.

**Comment by reindernl** [comment]
Hi,

Thanks for the huge help by explaining the issue you experience so well. That's really appreciated.

I actually reworked Mollie Components quite a bit. In the upcoming version (released this week) Mollie Components is actually a storefront plugin in stead of a seperately loaded javascript. I reworked the locale part and also the way variables are loaded. This works far better and more efficient. I hope you'll like it.

My kind regards.

**Comment by reindernl** [comment]
@dl-mbegerau The new version is released. Please let us know if this works out for you.

**Comment by dl-mbegerau** [comment]
We will include your update in our next release next week. I will let you know if everything works.

**Comment by dl-mbegerau** [comment]
Hey, thanks for the work! I think it's a great idea to use a shopware javascript plugin instead of a separate file. Unfortunately we encountered a couple of problems.

Environment changes compared to original post (completely new and clean shop):
Shopware: 6.2.0
Mollie: 1.0.13

### 1. The Language object is null in sales channel context
As I wrote in the original post the language object in the sales channel context seems to be null but the language id is defined.

_image: $language is null because language object in context is null_
![language-object-null](https://user-images.githubusercontent.com/57012534/83956532-cb38ae80-a824-11ea-873b-7edeab6624ba.png)

This means that the getLanguage() in CheckoutConfirmPageSubscriber.php on line 112 will return null. But getLanguageId() returns the language id.

If you add the language repository in your services.xml via `<argument type="service" id="language.repository" />` to the subscriber you can pick up the language id from the context and search for the language entity. You can find an example in my original post.

### 2. Fallback submit is always called
I'm not sure why you added this (did not exist in 1.0.10) but now you have a fallback submit for the payment method form in creditcard-components.plugin.js on line 162:

```
160                // Fallback for submitting the form
161                setTimeout(function () {
162                    paymentForm.submit();
163                }, 2000);
```

The problem is, that this submit is always called even if there are missing or invalid data in the input fields.

_image: Clicking the save-button reloads the page although input data is invalid_
![fallback-submit](https://user-images.githubusercontent.com/57012534/83956821-9a0dad80-a827-11ea-92be-82c32e7b2653.gif)

### 3. Not compatible with 6.1.x
On Shopware versions older than 6.2.0 your script will cause an exception because it uses "async".

_image: Error in console on older Shopware versions_
![regenerator-runtime](https://user-images.githubusercontent.com/57012534/83956902-3a63d200-a828-11ea-97cd-ea408ecfb7e4.png)

The problem is that Shopware imports '@babel/polyfill' only since 6.2.0. So in older versions "async" functions could not be used in the shopware js plugins.

Compare polyfill loader 6.2.0 vs 6.1.6:
https://github.com/shopware/storefront/blob/v6.2.0/Resources/app/storefront/src/helper/polyfill-loader.helper.js
https://github.com/shopware/storefront/blob/v6.1.6/Resources/app/storefront/src/helper/polyfill-loader.helper.js

You can remove this exception for older Shopware versions by adding `import 'regenerator-runtime'` to your main.js or by using oldschool Promise/Defer functions.

**Comment by dl-mbegerau** [comment]
Hey, I just tested this with Shopware 6.2.2 and Mollie 1.0.15:
And there are no changes to the respective files, so the problem still exists.

**Comment by milan-kiener** [comment]
@dl-mbegerau This issue was never closed. Can you please let us know if you still experience trouble with this?

**Comment by milan-kiener** [comment]
@dl-mbegerau We ha
