### ISSUE TITLE
Plugin doesn't work if vertical tax mode ist selected in sales channel

### ISSUE THREAD

**Issue by theDyingMountain** [mollie/Shopware6#170]
If vertical tax calculation is selected in the sales channel, the amount of the items and the total amount do not match because of rounding differences. I got the following error:

`An error occurred during processing the payment
{"orderTransactionId":"5f6a50521f66465f84086b5d74b6fbfa","exceptionMessage":"Could
not create a Mollie payment url due to the following error: Could not
create Mollie order, error: [2021-07-28T11:49:16+0000] Error executing
API call (422: Unprocessable Entity): The amount of the order does not
match the total amount from the order lines. Expected order amount to be
€29.01 but got €29.00. Field: amount.`

I think this is because the tax is calculated for each in Item in [Pricecalculator line 37](https://github.com/mollie/Shopware6/blob/master/src/Service/MollieApi/PriceCalculator.php#L37)

**Comment by schmitzcarsten** [comment]
@theDyingMountain would you please provide additional infos to configured tax rates, net/gross configuration, lineitem quantity and price. Thx in advance

**Comment by schmitzcarsten** [comment]
@theDyingMountain I really need more information from you. I can't reproduce the problem at the moment.
