### ISSUE TITLE
Mollie can't return to finish page when saleschannel is not root domain

### ISSUE THREAD

**Issue by Bernardus** [mollie/Shopware6#176]
Hi There,

The domain of my saleschannel is domain.com/nl and domain.com/en.
After going to the mollie external enviroment it sends me back to domain.com/mollie/payment/ instead of domain.com/nl/mollie/payment.

`Error: Uncaught Shopware\Storefront\Framework\Routing\Exception\SalesChannelMappingException: Unable to find a matching sales channel for the reques
`
It works when i add the /nl in the url

Shopware v6.4.1.1 Stable Version
Mollie plugin Version: 1.5.1

**Comment by schmitzcarsten** [comment]
we changed the router from symfony to shopware router in v1.5.2. It should wrk with this version.
