### ISSUE TITLE
API: Order create request fails because of invalid "expiresAt" due to timezone difference

### ISSUE THREAD

**Issue by dl-mbegerau** [mollie/Shopware6#19]
### Environment

OS: Ubuntu 18.04
Apache: 2.4.29
PHP: 7.3.17
MySQL: 5.7.30
Shopware: 6.1.5 (fresh installation from production repository)
Mollie: 1.0.10
Other Plugins: Shopware 6 Demo data (1.0.5)

### Problem
Every night between midnight and 2am all payments fail because Mollie rejects the request to the order create endpoint.

### Detected causes
https://docs.mollie.com/reference/v2/orders-api/create-order

The API documentation states:
> The date the order should expire in YYYY-MM-DD format. The minimum date is tomorrow and the maximum date is 100 days after tomorrow.

custom/plugins/MolliePayments/src/Handler/PaymentHandler.php, line 447
`447            $dueDate = $settings->getOrderLifetimeDate();`
            
custom/plugins/MolliePayments/src/Setting/MollieSettingStruct.php, lines 166-168
```
166        return (new DateTime())
167            ->modify(sprintf('+%d day', $this->getOrderLifetimeDays()))
168            ->format('Y-m-d');
```

$this->getOrderLifetimeDays returns the config value for the field "Order Lifetime Days". Or 1 by default.

Shopware sets the default timezone to UTC (my Server default timezone is America/NewYork).

It seems like the Mollie API uses CET. Now in summertime UTC is 2 hours behind CET.
That means from midnight until 2am the "+%d day" which is "tomorrow" for the script results in "today" for the Mollie API which is why it rejects the request.

### Solution suggestion
a) Change the timezone for this part of the script (might harm other time related data).
b) Add the time difference between php and CET to the datetime object.

### Current workaround
We just set the "Order Lifetime Days" config value to a value greater than 1 for now (previously undefined).

**Comment by reindernl** [comment]
Thanks for the effort you put into reflecting on the issue. I feel for solution b. Seems like the cleanest way to handle this issue. Do you agree?

**Comment by willemstuursma** [comment]
Are you sure Mollie doesn't use UTC?

@MollieRick @ndijkstra

**Comment by MollieRick** [comment]
I think we have a bug here. It should be UTC but we parse it with a timezone. I'll check it Monday.

**Comment by MollieRick** [comment]
We handle dates as UTC, also in the Orders API

**Comment by willemstuursma** [comment]
So the date has to be provided in UTC right?

So the code example should have a `->setTimezone()` invocation in there.

**Comment by dl-mbegerau** [comment]
Hey guys, I thought maybe it helps you if I deliver some evidence. I do think that the API uses UTC but maybe not for the expiresAt day validation. Maybe it uses the timezone where the merchant is registered.

Well let's go to the evidence. The code snippet I show is from mollie php api package. It's the function `rest_create` inside EndpointAbstract(line:71) called from OrderEndpoint(line:54) called from PaymentHandler(line:509). It's right before and after the API request is send to Mollie. The system is a fresh Shopware installation, besides Mollie only the official demo data plugin is installed. I buy the same product and use the same user and same payment method in each test.

1st test: Right before midnight in Central Europe.
UTC: May 19, 21:54
CET: May 19, 23:54
![Screenshot from 2020-05-19 23-54-27](https://user-images.githubusercontent.com/57012534/82402352-cbae0880-9a21-11ea-9728-d9648bdfa00f.png)

![Screenshot from 2020-05-19 23-55-57](https://user-images.githubusercontent.com/57012534/82402453-0152f180-9a22-11ea-84ae-5026b5c7395a.png)
Everything works fine. Mollie returns with status: created. Actually in the result we see that Mollie returns the createdAt and expiresAt in UTC timezone.


2nd test. Right after midnight in Central Europe.
UTC: May 19, 22:05
CET: May 20, 00:05
![Screenshot from 2020-05-20 00-05-00](https://user-images.githubusercontent.com/57012534/82402587-6d355a00-9a22-11ea-9128-392607880977.png)
![Screenshot from 2020-05-20 00-05-48](https://user-images.githubusercontent.com/57012534/82402596-758d9500-9a22-11ea-8b7e-1340b53776ed.png)
We see that Shopware still sends the 20th of May as exiresAt date. So we can be sure that Shopware uses UTC or at least a timezone west of Central Europe.
Now the test fails. Mollie returns the following error:
>  Error executing API call (422: Unprocessable Entity): Expiry date is invalid. Please provide the expiryDate in yyyy-mm-dd formt.. Field: expiryDate.


3rd test: Right before midnight in UTC.
UTC: May 19, 23:51
CET: May 20, 01:51
![Screenshot from 2020-05-20 01-51-55](https://user-images.githubusercontent.com/57012534/82402824-fba9db80-9a22-11ea-8afd-ea90871b2aee.png)
Mollie returns the same error as before. Shopware and Mollie API still seem to be not on the same day.


4th test: Right after midnight in UTC.
UTC: May 20, 00:05
CET: May 20, 02:05
![Screenshot from 2020-05-20 02-05-35](https://user-images.githubusercontent.com/57012534/82402916-3a3f9600-9a23-11ea-91a4-65abd2041017.png)
![Screenshot from 2020-05-20 02-07-24](https://user-images.githubusercontent.com/57012534/82402919-3d3a8680-9a23-11ea-9cd2-a1ab101c0169.png)
Shopware now sends May 21st as expiresAt date. So now we can be pretty sure that Shopware uses UTC, also `date_default_timezone_get` returns UTC. Mollie accepts the request again and returns a created order.


This is what happens to us every night. It seems to me that Mollie API uses CET to check the expiresAt date. Maybe this is because our merchant is located in Germany. In that case the Mollie plugin in Shopware should be aware of that. In any case, both sides should use the same timezone.

As I wrote in the original post, our current workaround is to set the expiry days config value to at least 2 in our shops. But by default it is unset, so I guess more shops have this problem. Luckily there is not much traffic going on between midnight and 2am.

If this error is somehow related to our server setup or our Mollie configuration, please let me know.

**Comment by willemstuursma** [comment]
I'll look into this and check on our (Mollie's) end.

**Comment by willemstuursma** [comment]
We were comparing against local time instead of UTC. We will deploy a fix early next week.

**Comment by reindernl** [comment]
We also now push the UTC timezone, see:
https://github.com/mollie/Shopware6/blob/master/src/Setting/MollieSettingStruct.php#L192

So with Mollie's fix that's about to be deployed next week, thinks should work out.

**Comment by willemstuursma** [comment]
This has been resolved on our end @reindernl. It should be good now, please let me know (here) or via Slack if you have further problems.

**Comment by dl-mbegerau** [comment]
Hey, thanks for the effort. I can confirm that it's working now. I just tested at 0:30 am CET.

Environment changes compared to original post (completely new and clean shop):
Shopware: 6.2.0
Mollie: 1.0.13
