### ISSUE TITLE
I need to see the credit card type in the order

### ISSUE THREAD

**Issue by azngeek** [mollie/Shopware6#212]
I need to submit the type of the credit card (amex, visa, master) to the ERP. In order to this, this information should be present in the API-response. This is what we have right now. Maybe this could be added into the custom fields?

` 
{
      "id": "...",
      "type": "payment_method",
      "attributes": {
        "pluginId": "...",
        "name": "Credit card",
        "distinguishableName": "Credit card | Mollie Payments",
        "description": null,
        "position": 2,
        "active": true,
        "afterOrderEnabled": false,
        "customFields": {
          "mollie_payment_method_name": "creditcard"
        },
        "availabilityRuleId": null,
        "mediaId": "...",
        "formattedHandlerIdentifier": "handler_kiener_creditcardpayment",
        "createdAt": "2021-10-05T14:04:23.137+00:00",
        "updatedAt": "2021-10-25T09:20:36.581+00:00",
        "translated": {
          "name": "Credit card",
          "distinguishableName": "Credit card | Mollie Payments",
          "description": null,
          "customFields": {
            "mollie_payment_method_name": "creditcard"
          }
        },
        "apiAlias": null
      }
`

**Comment by boxblinkracer** [comment]
I haven't yet tested the PR
but it it has been implemented and will be released soon, once tests pass

heres the PR
https://github.com/mollie/Shopware6/pull/381

**Comment by boxblinkracer** [comment]
done, coming in next version

**Comment by boxblinkracer** [comment]
released with v3.0 :)
