### ISSUE TITLE
NPM ^7 and ^8 fail to install mollie-shopware6-administration-tests and mollie-shopware6-storefront-tests

### ISSUE THREAD

**Issue by AndreasA** [mollie/Shopware6#218]
With current shopware production template all plugin dependencies call a `npm install` for all installed plugins in admin and storefront build processes:
https://github.com/shopware/production/blob/v6.4.5.1/bin/build-storefront.sh#L32

This means that the npm install is triggered for your tests and it currently fails with a newer NPM version than 6.x

Though I think the installation isn't required at all, see: https://github.com/mollie/Shopware6/issues/217

**Comment by boxblinkracer** [comment]
Hi there

thanks for this

i was able to reproduce it.
so not compatible with npm 7 and 8

no high prio problem at the moment
but I'll solve it :)

thanks

**Comment by boxblinkracer** [comment]
oh sorry,
has been released with v2.0
