### ISSUE TITLE
Add package-lock.json file for administration and storefront npm install

### ISSUE THREAD

**Issue by AndreasA** [mollie/Shopware6#219]
With current shopware production template all plugin dependencies call a `npm install` for all installed plugins in admin and storefront build processes:
https://github.com/shopware/production/blob/v6.4.5.1/bin/build-storefront.sh#L32

This means that the npm install is triggered and currently there is no package-lock.json so it might result in wrong dependency versions being installed.

However, I think the installation isn't required at all, see: https://github.com/mollie/Shopware6/issues/217

**Comment by boxblinkracer** [comment]
Hi

thank you for this

yes you are right
at the moment theres no lock file.
might have been missed in git

ill add it :)
should definitely be in there

**Comment by boxblinkracer** [comment]
locks are now existing in the main branch in the upstream :)
thank you for reporting this
