### ISSUE TITLE
Question: Creating open payment upon payment error with mollie workflow by design?

### ISSUE THREAD

**Issue by AndreasA** [mollie/Shopware6#223]
In `\Kiener\MolliePayments\Facade\MollieOrderPaymentFlow::process` you create a new open payment upon a failed payment. However, as you do not yet know if the user will start the payment process again, isn't this too early or is that required for the mollie payment checkout?

The main issue I have with this is that the payment method is not stored which results in restarting the transaction with a headless approach after setting the corresponding payment method that the payment select page opens instead of the intended pay page.

In `\Kiener\MolliePayments\Service\MollieApi\Order::createOrReusePayment` a payment would be created if it is missing with the corresponding payment method.

Due to https://github.com/mollie/Shopware6/issues/220 I cannot use the Shopware default workflow as I need to know if the payment was canceled or failed which I currently determine due to the order state but that is always canceled then.

In any case it would be nice to disable this.

**Comment by AndreasA** [comment]
I am also asking because apparently that open payment is not cancelable according to mollie. Not sure why an open payment isn't cancelable though.

**Comment by AndreasA** [comment]
Also for some reason my payment (in test mode) is always non cancelable which creates further issues.

**Comment by boxblinkracer** [comment]
Hi

thanks for this

I know that there are some requirements though
so while in Shopware 5 for example, every new payment attempt creates a new transaction/order in Mollie,
in Shopware 6 its all about 1 Mollie order with multiple transaction attempts.

So in general this is the better approach speaking of structure, but also the more complex one.

We have already planned to go over that and figure out, what to keep and what to remove.
so the target is definitely to have a better and linear flow in the end

i'll add that to the roadmap now, and will consider it when refactoring that

thanks for this

**Comment by AndreasA** [comment]
Using one payment and one order is definitely preferred. Sadly it has some drawbacks that still require a new order, see e.g. https://github.com/mollie/Shopware6/issues/225

Maybe you can actually get in touch with Mollie API developers and ask them to make all open payment cancelable because that one is a huge issue.

**Comment by boxblinkracer** [comment]
hi @AndreasA 
so the confusing and mixed usage of the order transactions have now been improved and fixed in v2.2.0.

i did also go through the createOrReuse payment, and it all worked for me.
so i guess we can close this for now?

unfortunately a 1:1 creation of orders will not happen for now. so 1 order can have multiple transactions...but as mentioned, this should now work with the approach of multiple shopware transactions too :)

**Comment by AndreasA** [comment]
@boxblinkracer I will need to test it but I am not sure when I will find the time, especially, as with latest versions of the plugin I was able to switch to default Shopware 6 workflow.

In any case, as long as the payment is not immediately created upon a failed payment but only once it is needed, it should be fine because that was the main issue previously.and resulted in an exception when trying to pay again.

The reason is that the user was able to switch the payment method later one which is done by creating a new order transaction but the previous payment was reused which already had a payment method set-


So as long as upon changing the payment method for a new order transaction after a previous payment failed and mollie opening the correct payment page for that payment method for both possible workflows (mollie plugin specific and default Shopware 6) occurs, it should be fine and the issue can be closed.
