### ISSUE TITLE
Standard Shopware error handling and non cancelable payment results in the previous payment page being opened on Mollie checkout

### ISSUE THREAD

**Issue by AndreasA** [mollie/Shopware6#225]
If I use the standard Shopware default error handling and during payment close the window, change the payment and restart the payment later on (e.g. order history), then the previous payment method is still pre-selected because the existing payment is not changed or canceled. However, changing the payment method on a payment with a selected payment method is not possible either. 

Maybe canceling the whole order and re-creating it instead would work?

Not sure why that payment is not cancelable but for me in test mode I never found a cancelable payment which is kind of weird though.

**Comment by AndreasA** [comment]
After checking issues in the mollie php api client apparently most payments now are non cancelable. Therefore, the only solution I can think of in this scenario is to create a new Mollie order, if there is an open payment and the Shopware default error handling is used and let the previous order and payment expire. It isn't perfect but better than using the wrong payment.

And I would also forward such scenarios to Mollie, there really shouldn't be a reason for the payment not being cancelable, especially as the user themself can cancel the payment. I admit it is an edge case but with headless setups e.g. apps that use Shopware headless, this can be a real scenario as the external payment window can easily be closed.

**Comment by AndreasA** [comment]
So to summarize the steps:

- Login in Shopware frontend.
- Set Mollie plugin to use "Standard failed payment workflow"
- Start payment process for payment method `A`.
- Close browser.
- Login in Shopware again.
- Go to order history, change the payment method to method `B` and finish payment.

The payment method used by mollie will now be still method `A`, instead of `B`.  I admit it is and edge case but it is not impossible. Especially with headless / API approaches in apps.

**Comment by boxblinkracer** [comment]
Hi again

thanks for this
perfect, that is also another internal ticket that I have as TODO :)

it should of course change
so what I once tested is, that the webhook should change the payment method (but as mentioned, I have to double check this).
did you test with or without webhooks?
so maybe its already being changed,
but anyway...i have to double check it too :)


great job with all this
thanks a ton

**Comment by boxblinkracer** [comment]
Hi there

I'm currently planning new features
thank you for your description
i think that should do for now

I'm digging deeper when I start this ticket :)

**Comment by BlackScorp** [comment]
@AndreasA 

i tried to reproduce the error in order to fix the bug, but it seems like it was fixed by another ticket. 

can you try it again? i assume there is no issue anymore. if everything works as expected we can close the ticket

**Comment by AndreasA** [comment]
Hi @BlackScorp I am not sure when I will find the time to retest this. 

If you think it is fixed, I am fine with closing the issue and if I have time and the issue still exists I will create a new issue and reference this one.
