### ISSUE TITLE
LoggerService doesn't limit message length

### ISSUE THREAD

**Issue by soebbing** [mollie/Shopware6#23]
Hi there!

The `Loggerservice` doesn't enforce the maximum message length defined in the `log_entry` table. 

Messages can only be 255 chars long, this length exceeded during checkout with the klarna "Slice It" payment in our case (the payment wasn't available in our country, resulting in a longer error message).

Changing the line 54 in the `LoggerService` by adding a `mb_substr()` call, reducing the length to 255 chars fixed the issue in our case.

**Comment by reindernl** [comment]
Hi Soebbing,

Thanks for contacting us. We actually found this issue ourselves already and fixed it with a mb_substr 😊

My kind regards,
Reinder.
