### ISSUE TITLE
Unable to find a matching sales channel 

### ISSUE THREAD

**Issue by sdobbelaere** [mollie/Shopware6#25]
After a successful payment one is redirected to a page like:
https://www.example.com/mollie/payment/somehash

We have set up the configuration to use
https://www.example.com/nl-be/
https://www.example.com/en-gb/

In this setup the redirect-urls don't seems to work.

Shopware 6.2
Mollie 1.0.13

<img width="1074" alt="Screenshot 2020-06-01 at 20 12 09" src="https://user-images.githubusercontent.com/16462709/83439873-3a3c8e80-a444-11ea-85a8-048e5c33e53e.png">

I'm happy to provide further info.

**Comment by milan-kiener** [comment]
This issue is resolved in the release 1.3.1
