### ISSUE TITLE
CreditCardComponents not usable in Shopware AccountOrderController

### ISSUE THREAD

**Issue by jleigers** [mollie/Shopware6#261]
After any payment failed for a customer in Shopware he will get redirected to a edit order page (AccountOrderController::editAction). On this page the customer is requested to finalize the payment for his order.

Unfortunately the Mollie integration is not working on that page and credit card data cannot even be entered into the shown input fields.

**Comment by boxblinkracer** [comment]
Hi 

thank you for your issue
I hope you had a great christmas time

This is planned for the next release in january :)
so I guess that is ok then

**Comment by boxblinkracer** [comment]
released with v2.0.0
