### ISSUE TITLE
Mollie Plugin throws exception when refunding through PayPal

### ISSUE THREAD

**Issue by fjbender** [mollie/Shopware6#269]
Steps to reproduce
- Have an order paid with the [SwagPayPal](https://github.com/shopwareLabs/SwagPayPal) plugin
- Issue a refund in the Administration by opening the order, switching to the PayPal tab, clicking the refund button and confirming in the modal

Expected behavior
- The refund will go through. Mollie will not be involved, as this is handled by the PayPal plugin

Actual behavior
- Mollie will throw the following exception:
```
Uncaught PHP Exception Kiener\MolliePayments\Exception\CouldNotExtractMollieOrderIdException: "Could not extract the Mollie Order ID for order with number 20000083" at /app/custom/plugins/MolliePayments/src/Service/OrderService.php line 129 {"exception":"[object] (Kiener\\MolliePayments\\Exception\\CouldNotExtractMollieOrderIdException(code: 0): Could not extract the Mollie Order ID for order with number 20000083 at /app/custom/plugins/MolliePayments/src/Service/OrderService.php:129)"}
```
- The refund will still go through, but confirmation in the user interface is inhibited by our exception, which is confusing to Administration users

**Comment by daniel-memo-ict** [comment]
Hi Florian,

This will be resolved in the next release. 

I quickly looked at the SwagPayPal plugin and they seem to [set the order transaction state to refunded](https://github.com/shopwareLabs/SwagPayPal/blob/master/src/Util/PaymentStatusUtilV2.php#L41) (as they should.) The current version of the Mollie plugin still [listens for this state change](https://github.com/mollie/Shopware6/blob/v1.5.8/src/Subscriber/PaymentStateSubscriber.php#L43) and then tries to do a refund in Mollie, which obviously isn't possible.

**Comment by niklaswolf** [comment]
@daniel-memo-ict hi, does "next" release mean the new 2.0.0 release? So this is not an issue anymore?

**Comment by daniel-memo-ict** [comment]
Hey @niklaswolf,

Yes, the automatic refund that happened when the payment status changes has been removed, in favor of a flow builder action that you can add to achieve the same result.

As for shipping, while the automatic shipping on state change still exists, it is now configurable in the plugin configuration and is disabled by default. Of course, there's also a flow builder action that can be used for this. I would not advice using both methods at the same time, though.
