### ISSUE TITLE
Multiple paid transactions per order, despite not being paid in Mollie

### ISSUE THREAD

**Issue by fjbender** [mollie/Shopware6#270]
Steps to reproduce
- Create an order in the Frontend, but cancel payment and use a different payment method multiple times (e.g. 3)
- Set payment state to paid on last payment

Actual result
- For the given order (ord_g2uf2e) there are two transactions marked as paid (tr_mFQM8HmRdp -> correct and tr_NMCUDeMxu8 -> incorrect)
![image](https://user-images.githubusercontent.com/7370694/149377227-15ffe07f-96ba-4e7c-bce1-95da3fef54c7.png)
- For Mollie, only tr_mFQM8HmRdp is paid, tr_NMCUDeMxu8 is canceled. Actual payment states for this order at Mollie are:

Token | Description | Method | Status | Created | Amount
tr_NMCUDeMxu8 | Order 10096 | Pay later. | cancelled | Jan 4, 2022, 3:36:13 PM | €977.00
tr_NH9hTbRKf6 | Order 10096 | giropay | failed | Jan 4, 2022, 3:37:23 PM | €977.00
tr_mFQM8HmRdp | Order 10096 | iDEAL | paid | Jan 4, 2022, 3:37:47 PM | €977.00

- Interesting to see is that the `updated_at` timestamps for both paid transactions are very closely together. Webhook runtime on my setup usually is 1-2 seconds as well, so it might be that for some reason the same webhook updated two transactions

Expected result
- Transaction state at Mollie and in Shopware are synchronous

**Comment by boxblinkracer** [comment]
the order transactions have been updated with a latest commit.
this is important for all additional payment attempts when the first payment fails

when switching to a new payment method, a new order transaction is created in shopware.
mollie will get the correct (new) one for the webhook.
however, once paid, mollie will always use the initial order-transaction ID from the initial webhook

thats why the webhook endpoint in the plugin always makes sure to always add status updates on the latest/recent order transaction only in shopware

i guess that should then all work @fjbender ?

**Comment by fjbender** [comment]
It should, yes. Thanks!
