### ISSUE TITLE
Support for subscriptions

### ISSUE THREAD

**Issue by azngeek** [mollie/Shopware6#298]
Subscriptions are a feature which are currently not implemented. However this is a feature which is required by some merchants. 

Could this be in the scope of a future implementation? If so, i could provide some more details about some specific implementation scenarios.

**Comment by boxblinkracer** [comment]
hi

thanks for this
its already in progress :)

**Comment by azngeek** [comment]
Oh okay, very nice :)

**Comment by boxblinkracer** [comment]
:)
it will still take a bit, but I guess you should recognize it when being released :)

**Comment by azngeek** [comment]
Are there any update on this topic?

**Comment by boxblinkracer** [comment]
hi
yes, if you look at the pending PR that i'm just at the moment about to finalize you see that we are almost done :)
https://github.com/mollie/Shopware6/pull/325

i hope this helps

**Comment by azngeek** [comment]
It seems like the current PR for subscriptions was closed. Is there any update on this?

**Comment by boxblinkracer** [comment]
yes its merged into the separate feature branch in the upstream.
while its currently in BETA testing (managed by mollie)
i'm doing some small additional features

**Comment by boxblinkracer** [comment]
this has been released in v2.3.0
