### ISSUE TITLE
Order gets reopened when in Status "closed".

### ISSUE THREAD

**Issue by azngeek** [mollie/Shopware6#303]
When i create an order and the order-status is "completed", any other change in the payment status will reopen an existing order. This is a behaviour where an implicit dependency exists between two different state machines. 

Is this an expected behaviour?

**Comment by boxblinkracer** [comment]
i havent heard about that
is it possible to reproduce it, can i have the step-by-step instructions?

in addition to this, just today a new PR was merged that handles wrong order transactions and how they are shown and handled in the administration. maybe that has to do with it

**Comment by azngeek** [comment]
1. Create an order
2. Pay with any payment type
3. Close the order in the Backend (set order state to closed)
4. Wait until the order gets confirmed (payment state = paid)
5. The order gets reopened.

**Comment by azngeek** [comment]
Yes, a closed order is an order in status "done", you are right.

- There is no flow in the flow-builder which reopens a process if an authorized payment is set to "paid". 
- We do have order-status Mapping enabled, but this should only trigger it the order is created. There might be an issue with that setting. 

![image](https://user-images.githubusercontent.com/213429/156542492-6624f2df-a5e7-48fe-9943-274907a7655c.png)

**Comment by boxblinkracer** [comment]
Hi
why do you think it should be triggered if created? thats not what this feature does.
your configuration says, once a transaction is "paid" which happens after a while with pay later (due to the authorization first), then the order should have "In Bearbeitung".

this mapping is the reason why the plugin transitions it...

why cant you just set that to "done" in the mapping for "paid"...because it seems as if paid payments should lead to an order "done" in your case?

**Comment by azngeek** [comment]
- Thanks for the clarification. I guess this is something which i just expect to work the way.
- We do have several other states which need to be processed in a given order.

I am still curious about, how a transition from "done" to "in progress" is possible as the following transitions must be done:

1. done to open
2. open to in progress

So the current implementation can automatically traverse through all possible transitions for any state and chooses the right one which will then lead to "in progress"?

**Comment by azngeek** [comment]
Yes exactly. Symfony has a nice feature which is used to "guard" certain transitions. Basically exactly what you said:(https://symfony.com/doc/current/workflow.html#guard-events).

I now understand the logic behind that feature but i also assume that other customer will face the same situation. I guess sometimes you just expect certain conditions instead of exactly reading the description. :)

**Comment by Bernardus** [comment]
We see this behaviour in our return process.

To generate a creditnote in shopware, we need to edit the order itself. This results in an open orderstatus.
After a creditnote is generated we refund the order through the mollie extension and manually set the orderstatus to done.

The refund takes two hours, and after these two hours mollie updates the payment status to refunded or partially refunded. But after a while the orderstatus is switched to open again . This leads to reservation of the stock.

**Comment by boxblinkracer** [comment]
Hi there
just released the "Final Order Status" feature with v2.2.2
that should fix it right?
heres the guide: https://github.com/mollie/Shopware6/wiki/Order-state-automation
