### ISSUE TITLE
Exception IPAnonymizer since Shopware v4.8.0

### ISSUE THREAD

**Issue by WorksDev** [mollie/Shopware6#320]
I cannot estimate exactly when this will happen, but probably as soon as a provider makes only IPv6 addresses available to customers.

Message
Uncaught PHP Exception ErrorException: "Notice: Undefined offset: 1" at
/src/Service/Logger/Services/IPAnonymizer.php line 43

Parameter:
IPAnonymizer->anonymize ('2003:e3:e70c:4eaa:949d:x56x:3x68:xx12')
in custom/plugins/MolliePayments/src/Service/Logger/Processors/AnonymousWebProcessor.php (line 55)

**Comment by boxblinkracer** [comment]
hi
yes we have heard from this, i dont know if it was you.
its just not working for ipv6 unfortunately.
thank you for your pull request. this is a perfect timing, because i would have done it on monday :)
really helps a lot

thank you

**Comment by WorksDev** [comment]
Hi @boxblinkracer,

yes, I think the message came from us - the first PR was intended as a pure bug fix - I have now adapted the whole thing a bit, removed the IP anonymiser and replaced it with the existing Symfony counterpart and added a test.

**Comment by boxblinkracer** [comment]
hi @WorksDev 
perfect
great move, good idea on that
will be in the new version :)
