### ISSUE TITLE
Refund manager not compatible with multiple storefronts

### ISSUE THREAD

**Issue by MelvinAchterhuis** [mollie/Shopware6#330]
It seems that the refund manager uses the keys for "All Sales Channels" that are configured in the plugin configuration to look up the order. 

Our current setup is as following:

- All sales channels -> Nothing filled in
- Storefront 1 -> Unique test & live key
- Storefront 2 -> Unique test & live key

When opening an order in the admin the following error is thrown `Could not fetch the Mollie Order for ID ord_xxxxx`. 

When we fill in the keys from Storefront 1 in "All sales channels" refunds are working for orders that are placed on "Storefront 1", but not for orders that are placed on "Storefront 2".

**Comment by boxblinkracer** [comment]
Hi Melvin

sorry for this

its already fixed,
its an easy one, so you could apply it within your version too

https://github.com/mollie/Shopware6/commit/ccfa67dbbe222702bc8c4e207593b7244013c1ed

i hope this helps

**Comment by MelvinAchterhuis** [comment]
Didn't see that one, thanks for the reply @boxblinkracer !

**Comment by boxblinkracer** [comment]
always happy to help @MelvinAchterhuis :)

**Comment by boxblinkracer** [comment]
let me just open it again so that people see it (with the solved badge)

**Comment by MelvinAchterhuis** [comment]
```
[2022-04-08T10:57:35.898868+00:00] Mollie.INFO: Starting refund for order: 10000 (Session: ...) {"session":"","processors":{"uid":{"uid":"xxxxxx"},"web":{"url":"/api/_action/mollie/refund","ip":"127.0.0.1","http_method":"POST","server":"domain.test","referrer":"https://www.domain.test/admin"}}} []
[2022-04-08T10:57:35.986651+00:00] Mollie.ERROR: API error occurred when fetching mollie order ord_xxxxxx with message [2022-04-08T10:57:35+0000] Error executing API call (404: Not Found): No order exists with token ord_xxxxxx.. Documentation: https://docs.mollie.com/overview/handling-errors (Session: ...) {"session":"","processors":{"uid":{"uid":"xxxxxx"},"web":{"url":"/api/_action/mollie/refund","ip":"127.0.0.1","http_method":"POST","server":"domain.test","referrer":"https://www.domain.test/admin"},"introspection":{"file":null,"line":null,"class":"Kiener\\MolliePayments\\Service\\MollieApi\\Order","function":"getMollieOrder"}}} []
[2022-04-08T10:57:35.986741+00:00] Mollie.ERROR: Could not fetch the Mollie Order for ID ord_xxxxxx (Session: ...) {"session":"","processors":{"uid":{"uid":"xxxxxx"},"web":{"url":"/api/_action/mollie/refund","ip":"127.0.0.1","http_method":"POST","server":"domain.test","referrer":"https://www.domain.test/admin"},"introspection":{"file":null,"line":null,"class":"Kiener\\MolliePayments\\Controller\\Api\\RefundController","function":"refundAction"}}} []
```

Error is gone when opening the order with this fix -> https://github.com/mollie/Shopware6/commit/ccfa67dbbe222702bc8c4e207593b7244013c1ed, however when clicking the "Refund" button the error above is thrown for sales channels that have a different key then the "All sales channels" configuration

**Comment by boxblinkracer** [comment]
oh, so you mean when you proceed with the refund?
display error fixed, but refund itself not working?

**Comment by MelvinAchterhuis** [comment]
Correct!

**Comment by chefbuitenhuis** [comment]
@MelvinAchterhuis  asked me to add extra information to this ticket. We are integrating Shopware with the ERP of this particular customer. The API also does not mark the order items as returned for those sales channels, even though a full refund is performed:
`{
  "totals": {
    "remaining": 0,
    "voucherAmount": 0,
    "pendingRefunds": 0,
    "refunded": 40
  },
  "cart": [
    {
      "refunded": 0,
      "shopware": {
        "id": "...",
        "label": "....",
        "unitPrice": 35,
        "quantity": 1,
        "totalPrice": 35,
        "discountedPrice": 35,
        "productNumber": "....",
        "promotion": {
          "discount": 0,
          "quantity": 0
        },
        "isPromotion": false,
        "isDelivery": false
      }
    },
    {
      "refunded": 0,
      "shopware": {
        "id": "...",
        "label": "DHL",
        "unitPrice": 5,
        "quantity": 1,
        "totalPrice": 5,
        "discountedPrice": 5,
        "productNumber": "SHIPPING",
        "promotion": {
          "discount": 0,
          "quantity": 0
        },
        "isPromotion": false,
        "isDelivery": true
      }
    }
  ],
  "refunds": [
    {
      "id": "...",
      "orderId": "...",
      "paymentId": "...",
      "amount": {
        "value": "40.00",
        "currency": "EUR"
      },
      "settlementAmount": {
        "value": "-40.00",
        "currency": "EUR"
      },
      "description": "artikel niet op voorraad",
      "createdAt": "2022-04-11T13:15:43+00:00",
      "status": "refunded",
      "isFailed": false,
      "isPending": false,
      "isProcessing": false,
      "isQueued": false,
      "isTransferred": true,
      "metadata": null
    }
  ]
}`

**Comment by boxblinkracer** [comment]
hi
thank you for this.
so this is with the same problem with a custom sales channel with a separate api key?

there was another PR merged yesterday evening that fixes the refund execution (and not only the error that appears)
https://github.com/mollie/Shopware6/pull/335

i havent tested it yet, (i will do with the next release plan), but maybe it already helps you

**Comment by MelvinAchterhuis** [comment]
@boxblinkracer , fix above is not the solution. The refund goes succesfully to Mollie, however the line items aren't marked as refunded:
![Screenshot 2022-04-22 at 10 26 25](https://user-images.githubusercontent.com/26538915/164649705-76c15934-c4e9-4fac-8ff6-cd800c209d62.png)
![Screenshot 2022-04-22 at 10 27 30](https://user-images.githubusercontent.com/26538915/164649712-62489cad-b4ac-4f54-921a-37a30fc83c06.png)

**Comment by MelvinAchterhuis** [comment]
I've created a new ticket as the problem above isn't related to the Mollie API keys for different sales channels, that issue is fixed in the latest release.

**Comment by boxblinkracer** [comment]
Hi
i think i can close this issue? the storefront error is gone, now its only the maximum thing right @MelvinAchterhuis  ?

**Comment by MelvinAchterhuis** [comment]
Correct @boxblinkracer !
