### ISSUE TITLE
Ambiguous class resolution

### ISSUE THREAD

**Issue by WorksDev** [mollie/Shopware6#332]
When the extension is loaded via composer in a shopware System there are a lot of notices. Basically no problem, but very unattractive:

`Warning : Ambiguous class resolution, "Mollie\Api\Resources\CursorCollection" was found 2x: in "/builds/xxx/vendor/mollie/mollie-api-php/src/Resources/CursorCollection.php" and "/builds/xxx/vendor/store.shopware.com/molliepayments/vendor/mollie/mollie-api-php/src/Resources/CursorCollection.php", the first will be used.`

…..

**Comment by boxblinkracer** [comment]
Hi

I heard that this can happen because of multiple loadings when using the shopware composer way.
that is already on the list and will be improved, (not such a high prio at the moment)

thanks for reporting it
