### ISSUE TITLE
Header and Footer data returnFailedRedirect()  

### ISSUE THREAD

**Issue by wexosh** [mollie/Shopware6#336]
Hello, i have a question regarding the returnFailedRedirect() method in the PaymentController.php

I was wondering if there is any specific reason why the sales channels footer and header data is not passed to rendered storefont-view when returning to this route? :)
`@Route("/mollie/payment/{transactionId}"`

Right now the navigation and footer are not the same.
Some adjustments to the controller with a GenericPageLoader like this could maybe do the trick? 

Example:
`
return $this->renderStorefront('@Storefront/storefront/page/checkout/payment/failed.html.twig', [
            'page' =>
                [
                    'header' => $page->getHeader(),
                    'footer' => $page->getFooter(),
                    'metaInformation' => $page->getMetaInformation()
                ],
            'redirectUrl' => $this->router->generate('frontend.mollie.payment.retry', [
                'transactionId' => $transactionId,
                'redirectUrl' => urlencode($redirectUrl),
            ]),
            'displayUrl' => $redirectUrl,
        ]);
`

**Comment by boxblinkracer** [comment]
Hi

thank you for your message,
so basically, theres no reason for or against it, and also this is an old (but still valid) code.

what I know is that this is a technical URL that doesnt render anything
it processes the payment after the user has paid and then forwards to a failure or success page.

so i'm not quite sure why something should happen in there with headers and footer,
and I also never heard of anything regarding problems for this?

can you tell or show me a bit more what is happening?

thank you
