### ISSUE TITLE
Stock bug

### ISSUE THREAD

**Issue by powolnymarcel** [mollie/Shopware6#35]
Hello,
I'm getting in touch because I have noticed a very weird behavior with Shopware 6 .

Take a look at this scenario:
I have a "product A" with stock of 10 and set as closeout.
As a customer, I add product A to my cart, I click "pay" (with Mollie) when I am redirected to Mollie, the stock becomes minus 1 even if I haven't paid !
Next customer does the same thing but puts 9 remaining product A to his basket.
Shopware sets the stock to 0.
Third customer comes and nobody can buy product A anymore. And nobody has paid anything.
Am I clear in my explanations, is it me doing something wrong or it's a bug ?

I've set up Mollie to put the cancelled status on failed payments
https://i.ibb.co/9btTkHH/Capture2.png

As you can see here some customers attempted to buy something but for any reason changed their mind and the order is still "in progress"
https://i.ibb.co/w7MxTq6/Capture.png

The Mollie timeout is 15min right ?

**Comment by milan-kiener** [comment]
Hi Marcel, it is correct that the stock is reserved as long as the order is in progress, because you don't want to sell the same amount of products twice. The Mollie time out determines the transition to failed. Once failed, the stock should be available again.
