### ISSUE TITLE
Order being made twice

### ISSUE THREAD

**Issue by powolnymarcel** [mollie/Shopware6#36]
Hello,

I have noticed a strange behavior with the orders. I don't know if it's related to Shopware, Mollie or the customer himself.

Sometime orders are being added twice (two first rows and 2 last rows)
https://i.ibb.co/bmRdRXG/Capture.png

What do you think ?

*****
Got an answer from   boxblinkracer :  
Hi
alright so i've asked for more details in my company
the button events got triggered twice on double clicks
so what they basically did was to preventDefault after the first click, so its not fired twice
with that in mind, you could try to reproduce it and fix it.
please pay attention to additional events that might be chained and added to the onClick...just to say that :D
cheers
christian

**Comment by milan-kiener** [comment]
As far as we can see, this is a Shopware related issue indeed. You could prevent this by the solution Christian handed. Cheers, Milan
