### ISSUE TITLE
LineItemAttributes Struct is breaking on parsing custom fields

### ISSUE THREAD

**Issue by michnhokn** [mollie/Shopware6#380]
When parsing the custom fields the line items struct breaks searching the new structure if the value of `$lineItem->getPayload()['customFields']` is null.

https://github.com/mollie/Shopware6/blob/master/src/Struct/LineItem/LineItemAttributes.php#L197-L203
```php
# load the custom fields
$customFields = $lineItem->getPayload()['customFields'];

# ---------------------------------------------------------------------------
# search in new structure
   
$fullKey = 'mollie_payments_product_' . $keyName;
$foundValue = (array_key_exists($fullKey, $customFields)) ? (string)$customFields[$fullKey] : '';
```

`array_key_exists` can not work with null values. `$customFields` should be checked before.

**Comment by boxblinkracer** [comment]
Hi @michnhokn 
oh wow, that use case has slipped thru

thx so much, we'll add a fix and a unit test :)

**Comment by boxblinkracer** [comment]
Hi

a PR is already existing (https://github.com/mollie/Shopware6/pull/381)

thank you for telling us about this one

**Comment by boxblinkracer** [comment]
released in 2.3.1

**Comment by wexollm** [comment]
@boxblinkracer 
This is still an issue on version 2.5.0 of Mollie plugin, Shopware version 6.4.14.0

[2022-09-07T09:30:04.652639+00:00] request.CRITICAL: Uncaught PHP Exception TypeError: "array_key_exists(): Argument #2 ($array) must be of type array, null given" at /vendor/store.shopware.com/molliepayments/src/Struct/OrderLineItemEntity/OrderLineItemEntityAttributes.php line 139 {"exception":"[object] (TypeError(code: 0): array_key_exists(): Argument #2 ($array) must be of type array, null given at /vendor/store.shopware.com/molliepayments/src/Struct/OrderLineItemEntity/OrderLineItemEntityAttributes.php:139)"} []

**Comment by boxblinkracer** [comment]
Hi @wexollm 
a damn, because it has been fixed in the LineItemEntity attribute and not OrderLineItemEntityAttribute

cart vs. order....

I'll get it fixed, sorrry

**Comment by boxblinkracer** [comment]
Hi @wexollm 
heres the fix
https://github.com/mollie/Shopware6/commit/fd1d4e972c1564f9e39df4bba3f66bcd9b811482

comes next week :)

**Comment by wexollm** [comment]
@boxblinkracer 
great :)
