### ISSUE TITLE
Update to 2.3.0 shows this error:

### ISSUE THREAD

**Issue by csaeum** [mollie/Shopware6#383]
Update to 2.3.0 

`An exception occurred while executing 'INSERT INTO mail_template_type_translation (mail_template_type_id, language_id, name, created_at) VALUES (?, ?, ?, ?)' with params ["\x08\xda\xda\x27\xf1\x5e\x4d\x20\x94\x76\xcf\x6a\x8f\x27\xa8\x93", "\x2f\xbb\x5f\xe2\xe2\x9a\x4d\x70\xaa\x58\x54\xce\x7c\xe3\xe2\x0b", "Erinnerung der Abonnementverl\u00e4ngerung (Mollie)", "2022-07-23 12:38:29.611"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '\x08\xDA\xDA'\xF1^M \x94v\xCFj\x8F'\xA8\x93-/\xBB_\xE2\xE2\x9AMp' for key 'mail_template_type_translation.PRIMARY'`

The plugin has also been disabled.

**Comment by csaeum** [comment]
New Activate the Plugin show this:

`date(\"m \/ d \/ Y\", false) }}.
\nGesamtbetrag<\/strong>: {{ subscription.amount }} {{ subscription.currency }}
\n
\nDiese E-Mail soll Sie nur dar\u00fcber informieren, dass die Zahlung an diesem Datum erfasst wird.\n\nF\u00fcr \u00c4nderungen k\u00f6nnen Sie sich bei Ihrem Konto auf {{ salesChannel.name }} anmelden und das Abonnement jederzeit pausieren oder k\u00fcndigen.\n\nDanke\n{{ salesChannel.name }}\n", "Sehr geehrte(r) {{ customer.firstName }}\n\nGute Nachrichten!\n\nWir bereiten Ihr Abonnement f\u00fcr Sie vor.\n\nAbonnement: {{ subscription.description }}\nN\u00e4chste Verl\u00e4ngerung: {{ subscription.nextPaymentAt`

**Comment by boxblinkracer** [comment]
Hi @csaeum 
thank you
this is only in combination with a default language and has already been solved in this PR
https://github.com/mollie/Shopware6/pull/381

I plan to do a hotfix later this week (after testing)
if you are a developer, maybe you can also verify if that PR solves it on your end?

thanks

**Comment by boxblinkracer** [comment]
released in 2.3.1
