### ISSUE TITLE
All Subscription events should implement MailAware

### ISSUE THREAD

**Issue by michnhokn** [mollie/Shopware6#385]
All the Subscription events should implement MailAware.
Otherwise it is not possible to send Mails via the FlowBuilder to customers. I think this is the main purpose to have those events to greet a customer when a subscription is created or to thank him after a subscription is canceled.

![image](https://user-images.githubusercontent.com/38752255/180741763-26aea67d-f263-403e-8361-2e85d0069d44.png)

Currently on the `mollie.subscription.renewal_reminder` event implements MailAware.

Unfortunately, this is a real problem for us at the moment, because communication with the customers cannot really take place here.

**Comment by boxblinkracer** [comment]
Hi @michnhokn 

yes, makes indeed sense
i'll create an internal ticket to get it done :)

**Comment by boxblinkracer** [comment]
released in version 2.5
