### ISSUE TITLE
Return null is not allowed by return type hint.

### ISSUE THREAD

**Issue by SilvioPahrig** [mollie/Shopware6#39]
https://github.com/mollie/Shopware6/blob/c31c11a8cc15c6b4920f458cd748d59910f5a250/src/Handler/PaymentHandler.php#L501
an der Stelle wird null zurückgegeben, aber die methode muss ein array zurückgeben.

**Comment by milan-kiener** [comment]
@SilvioPahrig Theoretically it's impossible to reach this point in the code. But it would be better to throw an error, might this ever occur. We'll fix this in a near future release.

**Comment by milan-kiener** [comment]
@SilvioPahrig This issue is resolved in 1.3.6.
