### ISSUE TITLE
Subscriptions: Admin list should be searchable and filterable

### ISSUE THREAD

**Issue by michnhokn** [mollie/Shopware6#391]
Currently it is not possible for our customer support to find subscriptions based on customers or subscription ids.
With 2k+ subscriptions this is very annoying if you want to cancel one subscription.

It should be possible to filter and search in the administration for specific subscriptions.
Also it would be nice to filter for subscription tags: https://github.com/mollie/Shopware6/issues/390.

**Comment by michnhokn** [comment]
@boxblinkracer This would be very nice for our customer support with the new detail view in the administration.
Right now it is not really possible to find a subscription...

Maybe also a link from the customer directly to the subscription detail page would improve working speed in the admin?

**Comment by boxblinkracer** [comment]
implemented with 4.2.0
