### ISSUE TITLE
Payments with a country, which is tax free, lead to an exception

### ISSUE THREAD

**Issue by henrikvolmer** [mollie/Shopware6#4]
Steps to reproduce:

1. configure a country of your choice as a tax-free country
![Bildschirmfoto 2020-03-03 um 13 05 42](https://user-images.githubusercontent.com/25845699/75774236-d248b000-5d4f-11ea-8645-63dd2db4aa62.png)

2. create an account with exactly this country

3. make a payment (e.g. by credit card)

Result:

An exception is thrown.
![Bildschirmfoto 2020-03-03 um 13 08 44](https://user-images.githubusercontent.com/25845699/75780580-e7c3d700-5d5b-11ea-88a3-8e8a1784a9dc.png)

**Comment by KienerNL** [comment]
The price is now nullable. Thanks for your input.

**Comment by henrikvolmer** [comment]
Hey, 

thanks for the help, but the problem is not yet solved. In PHP, a "?" must be placed before a parameter to make it nullable. The "Nullcheck" was implemented, but the parameter was not made nullable.


![Bildschirmfoto 2020-04-20 um 13 10 02](https://user-images.githubusercontent.com/25845699/79745305-53f89b00-8308-11ea-8b1c-9a3fa9884598.png)

Could you please check it again :)
