### ISSUE TITLE
Default locale not working

### ISSUE THREAD

**Issue by IndeedEvan** [mollie/Shopware6#406]
Hi ! 😃 

I'm having an issue with default language on payment page, that page :
![Capture d’écran 2022-08-23 à 12 01 48](https://user-images.githubusercontent.com/12630507/186131047-66e0f9c3-3552-491f-a5df-92bf57c59ed6.png)
 
**Here is some context :** I use [Shopware PWA](https://github.com/vuestorefront/shopware-pwa) with Shopware v6.4.6.1 + Mollie payment module in last version and everything is working smooth so far.

I tried to change the default locale by editing sale channel locale and every URL connected without success, i tried modify Shopware PWA code to tweak the config of order/payment without success, i tried to replace `MOLLIE_DEFAULT_LOCALE_CODE` and [that line ](https://github.com/mollie/Shopware6/blob/a42110f0806ddec2a053b839754ee6d067bc968a/src/Service/MollieApi/Builder/MollieOrderBuilder.php#L146) without much success..

Do you have any idea what's happening ? Would it be possible to add a full override on mollie account or module config page ?

Thanks for maintaining the module it is awesome 💯

**Comment by boxblinkracer** [comment]
Hi @IndeedEvan 

first of all, thank you so much for your kind words :)
we're putting really so much effort in this plugin

i'm currently finishing the official support of headless and pwa
i didnt check the locale so far, but i'll pay attention..maybe its already fixed because the latest release doesnt yet fully support headles (officially)

**Comment by amin212121** [comment]
@IndeedEvan I've changed in sale channel Language and chose "Localisation according to ISO standard" and it helps me change Mollie checkout language from EN to De
