### ISSUE TITLE
Flow Builder: Mail Templates not assignable to events

### ISSUE THREAD

**Issue by LouisEiermann** [mollie/Shopware6#408]
At the moment only the trigger "Renewal Reminder" lets you assign a mail sending event. The other 4 triggers (p.e. "Started") do not let you assign a mail event. How can we send mails on these other triggers? Especially starting and cancelling are very relevant to customers.

**Comment by azngeek** [comment]
I guess this is a duplicate of https://github.com/mollie/Shopware6/issues/385?

**Comment by boxblinkracer** [comment]
Hi

thanks for this

yes duplicate and good thing...already developed and coming with one of the next releases :)

https://github.com/mollie/Shopware6/pull/405

**Comment by boxblinkracer** [comment]
released in version 2.5
