### ISSUE TITLE
Release for Shopware 6.4.15.1

### ISSUE THREAD

**Issue by shopkueche** [mollie/Shopware6#429]
Hello,

could you please set the Release-Version in Shopware-Store for the Mollie-Plugin for Shopware 6.4.15.1? Since 6.4.15.0 is compatible with Mollie it should also run on 6.4.15.1

Only change in 6.4.15.1 is bug regarding CLI Update process:
https://issues.shopware.com/issues/NEXT-23304

**Comment by boxblinkracer** [comment]
hi
i've updated it an hour ago
i actually already did it, but seems it was not saved, sorry :)
