### ISSUE TITLE
Refresh on payment error page starts default error handling

### ISSUE THREAD

**Issue by AndreasA** [mollie/Shopware6#43]
If, I reload on the custom error page - not the shopware default handling - it triggers the call to finalize transaction and the default finish url instead of staying at the error page.

However, it should still show the error page as the previous payment still failed. Apparently `paymentStatus` is set to `open` upon refresh. Which at this juncture should probably also show the error page or automatically redirect to `mollie.com`. 

however, it should not call finalize payment which apparently even triggers a redirect to the `finishUrl`.

**Comment by AndreasA** [comment]
I think the code shouild look something like this instead of the current version:
```
  if (
            $paymentStatus !== null
            && (
                $paymentStatus === PaymentStatus::STATUS_CANCELED
                || $paymentStatus === PaymentStatus::STATUS_FAILED
                || $paymentStatus === PaymentStatus::STATUS_OPEN
            )
        ) {
            $paymentFailed = true;
            if ($paymentStatus !== PaymentStatus::STATUS_OPEN) {
                $mollieOrder->createPayment([]);
            }

            if ($mollieOrder->getCheckoutUrl() !== null) {
                $redirectUrl = $mollieOrder->getCheckoutUrl();
            }
        }
```

**Comment by milan-kiener** [comment]
@AndreasA As stated on previous issues, please use the standard failed payment redirect to avoid this. You can enable it in the plugin configuration.

**Comment by AndreasA** [comment]
@milan-kiener Thanks for the feedback. We might intend to use the plugin in a headless configuration later on and the default failed payment handling by Shopware is not really usable there as it opens the account page or similar. In your case, only the failed payment page would need to be shown. I guess another alternative would be to create a redirect to the main page and implement an API to change the payment methods instead.
