### ISSUE TITLE
Wrong translation snippet key for payment method error

### ISSUE THREAD

**Issue by LouisEiermann** [mollie/Shopware6#437]
The error mollie-payments-cart-error-paymentmethod-availability has the wrong key in the german snippet (not the same as in the dutch/english snippet), this leads to the error not beeing translated correctly in german.

**Comment by boxblinkracer** [comment]
Hi @LouisEiermann 
ah perfect, thank you so much for this

perfect timing, I think I can fix it tomorrow for the next release

would you mind sending me the link to the file on github? 

thanks

**Comment by boxblinkracer** [comment]
thank you
its fixed and comes with the next release

**Comment by boxblinkracer** [comment]
released in v3.2.0
