### ISSUE TITLE
Display Subscription Interval on Product Detail Page 

### ISSUE THREAD

**Issue by LouisEiermann** [mollie/Shopware6#442]
1. Would you support adding a display of the subscription interval on the detail page of a subscription product? I already implemented this manually myself, and i could open a PR for this. If yes, should this display be controllable in the extension settings just like the option to display whether or not a product is a subscription product? I think adding this feature to the product page would benefit everyone using this extension.

2. Will you add the ability for the user to change the subscription interval himself in the storefront ? I suppose that would mean some bigger changes but do you have that in mind possibly in the future?

Let me know if you support 1. and if i should open a PR for it or if you have already planned something similar :)

**Comment by boxblinkracer** [comment]
Hi @LouisEiermann 
thank you

1.
mhm,...the PDP should already show the interval.
see the screenshot...doesnt it work on your side, or do you have other expectations?

2. atthe moment the subscription intervals are bound to the variant. so if you have different variants, then the user can already change it before purchasing it. we are also thinking about a way to keep the original product and add options to select available intervals for the purchase.
or do you mean to change an interval on a running subscription that is already purchased?

thank you :)

<img width="759" alt="Screenshot 2022-10-19 at 17 30 59" src="https://user-images.githubusercontent.com/5579326/196736768-b712e150-b8b9-4c69-a6aa-9857a48a1a2d.png">
