### ISSUE TITLE
Changing payment method in mollie - change not shown in order history in admin

### ISSUE THREAD

**Issue by AndreasA** [mollie/Shopware6#45]
The title says it all. If the user changes the payment method in Mollie, e.g. due to previous failed payment or using the corresponding option, the order's payment method of Shopware is not adjusted accordingly.

**Comment by milan-kiener** [comment]
Hi @AndreasA, please note my comment in your previous issue. You can choose the "failed payment redirect" in the plugin configuration to avoid this.

**Comment by AndreasA** [comment]
@milan-kiener This is not only rearding failed payments. I can also change the payment directly on the mollie checkout page. Or can this be disabled?

**Comment by AndreasA** [comment]
@milan-kiener 

Ah.. I just saw that doing so basically triggers failed payment handling. So it works fine. Thanks. I am now using the corresponding failed payment event listener to redirect accordingly which required a bit of a hacky workaround as the response cannot be adjusted there directly yet.
