### ISSUE TITLE
Payment with Klara "Pay later" can transition from "In Progress" to "Cancelled".

### ISSUE THREAD

**Issue by azngeek** [mollie/Shopware6#452]
**Status**

When a customer pays via Klarna Pay Later, we expect the payment status to be "in progress" when the payment is authorized and confirmed. 

The current state is that a customer, who pays via Klarna Pay and the payment has not been completed by the customer will result in a successfull payment. Please check the following history from the Mollie-Dashboard.

![image](https://user-images.githubusercontent.com/213429/202132779-e13377d3-4cfd-4369-8b74-d832b98c53cd.png)

This is the order-status in Shopware. As we could not find any other configuration option for this Payment-Type, it might be a bug. The problem is: The order gets processed by our ERP and the order will be sent to the customer. Two days later we get the information, that the order is not paid.

According to the documentation, the status should be "authorized". https://github.com/mollie/Shopware6/wiki/Klarna-Pay-Later

How can we solve this issue?

![image](https://user-images.githubusercontent.com/213429/202133283-0b011fd3-6f95-4f59-ba18-6caf6f3db202.png)

Update:

Could this option "Finaler Bestellstatus" could be responsible for this behaviour? Will this option not change the payment status or the order status?

![image](https://user-images.githubusercontent.com/213429/202138044-5c6c7c44-3e0b-4e46-b7b8-07f5b8bf65df.png)

**Comment by boxblinkracer** [comment]
Hi

so if I got you right, it's about the payment status?

then its right
the payment was created and expired, so its in progress and cancelled
your mollie dashboard does not show a correct payment. created is just initialized

if its authorized it looks like my screenshot.

![Screenshot 2023-01-13 at 13 56 20](https://user-images.githubusercontent.com/5579326/212325284-21736bf5-9983-445c-b796-0c4eabe31320.png)
