### ISSUE TITLE
Available payment methods on Mollie not limited to assigned payment methods of the current Sales channel

### ISSUE THREAD

**Issue by AndreasA** [mollie/Shopware6#46]
If I change the payment method at Mollie or if the payment fails, the user sees all in Shopware enabled payment methods. The assignment to the corresponding sales channel is ignored.

**Comment by milan-kiener** [comment]
Hi @AndreasA, this is correct. To avoid this, please choose the standard failed payment redirect (can be switched on/off in the plugin configuration).

**Comment by AndreasA** [comment]
@milan-kiener As far as I saw once I am on the mollie payment page, I can change the payment method there directly too which changing the payment fails handling will not resolve.
