### ISSUE TITLE
Support custom line item types or skip certain line items

### ISSUE THREAD

**Issue by AndreasA** [mollie/Shopware6#47]
Is it possible to skip certain line item types or add better support for custom line items in general as curretly all of those are marked as digital which might not be the case, e.g. in one project I added a custom type for surcharges.

As you do not need to add child line items (which would make it way too complicated anyway) it is not yet that big an issue but even the first line item level can have custom line item types.

**Comment by milan-kiener** [comment]
Unfortunately we're only supporting default Shopware line item types at this time.

You could try decorating `src/Service/OrderService` and adding support for your custom line item type to the `getLineItemType` function, as long as you return one of the `OrderLineType` constants. [Symfony's decorator pattern guide](https://symfony.com/doc/current/service_container/service_decoration.html)

**Comment by AndreasA** [comment]
Is using a decorator your recommended way here? If so, that is fine. was just wondering if you would prefer a different approach.

**Comment by AndreasA** [comment]
@milan-kiener Is using a decorator your recommended way here? 
If so, that is fine. was just wondering if you would prefer a different approach.
