### ISSUE TITLE
404 on store api routes

### ISSUE THREAD

**Issue by meeshoogendoorn** [mollie/Shopware6#472]
I have installed version 3.3.0 of the mollie plugin. I try to access the following store-api route from the shopware-pwa `https://my-domain.com/store-api/mollie/ideal/issuers` but every store api route from mollie will return 404. Is there something i need to setup or enable before being able to use the store api routes?

It will return the following response: 

```json
{"errors":[{"code":"0","status":"404","title":"Not Found","detail":"No route found for \u0022GET https:\/\/my-domain.com\/store-api\/mollie\/ideal\/issuers\u0022"}]}
```

**Comment by boxblinkracer** [comment]
Hi there

I'm working on headless at the moment and just tested it for you.
so it works on my end (screenshot)

is the plugin active and enabled? is the rest of the URLs working?
could you try our swagger sample, just to see if its working there for you?

maybe its also a proxy or setup related problem in your shop?
or cache clearing?

thank you

<img width="1100" alt="Screenshot_2022-12-08_at_13_38_54" src="https://user-images.githubusercontent.com/5579326/206448462-6b2695a7-eeb3-463c-bbd4-24d4e57a5606.png">

**Comment by meeshoogendoorn** [comment]
Sorry for this late response, It was something in the deployment, not related to the `mollie/shopware6` plugin 👍

**Comment by boxblinkracer** [comment]
Hi there

no worries :)
thanks for letting us know

merry christmas :)
