### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Moskydesign** [mollie/Shopware6#48]
When installing the plugin an error occurs when the custom fields are installed.

`"Expected primary key field id for definition Shopware\Core\System\CustomField\CustomFieldDefinition not provided"`

The error originates in the CustomFieldService.php on line 48.

When removing the "id" fields from the custom fields array the installation is successful, but the relations are mapped on these id's so that is not really a solution.

Using MolliePayments 1.3.6 and Shopware 6.3.3.1

**Comment by milan-kiener** [comment]
That error would imply that it's somehow missing an id, even though all custom fields are getting one.

It might be because we're still using hardcoded ids for custom fields, this will be fixed in an upcoming release. For now, you can try changing the hardcoded ids on line 44 to 47 to use `Uuid::randomHex()`. Make sure to include a using statement for `Shopware\Core\Framework\Uuid\Uuid` as well.

**Comment by Moskydesign** [comment]
Replacing the hard coded id's with the the generated once fixed that issue.
But now we get a second one:

```
An exception occurred while executing 'INSERT INTO `custom_field_set_relation` (`id`, `set_id`, `entity_name`, `created_at`) VALUES (?, ?, ?, ?)' with params ["\x29\x5a\x7e\xb1\xd2\x49\x4c\xc9\x92\x22\xc7\xd7\x87\xc6\x1e\xc6", "\xb3\x55\x7d\xf9\x90\x05\x4d\xbd\xba\x8b\x8b\x61\xfe\x2b\xd2\xb4", "customer", "2020-11-19 08:08:24.146"]:
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '\xB3U}\xF9\x90\x05M\xBD\xBA\x8B\x8Ba\xFE+\xD2\xB4-customer' for key 'custom_field_set_relation.uniq.custom_field_set_relation.entity_name'#0 /var/www/shopware/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(166): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
```

The problem is that according to this constraint the combination of the set_id and entity must be unique.
`uniq.custom_field_set_relation.entity_name  UNIQUE INDEX custom_field_set_relation(set_id ASC, entity_name ASC)`

However in the custom field definition the Customer Entity is used twice in the same set. Once for the Mollie customer ID and once for the Preferred iDeal issuer.

Since we don't need iDeal for this project we just removed that relation to make it work.

Exception aren't handled anyway so I don't expect many users to see this issue, when installing everything looks fine, except there aren't any custom fields created.
