### ISSUE TITLE
Wrong VAT calculation for summed up child line items

### ISSUE THREAD

**Issue by AndreasA** [mollie/Shopware6#49]
Related to https://github.com/mollie/Shopware6/issues/37

With the recent changes, most things seem to work fine but if one uses something like the bundle extension in the Shopware developer documentation.

Which creates something like a Product-Bundle-Line-Item that contains:

- Discount
- product 1
- product 2
- ....

This means that each child line item has its own rounded taxes. That means if I sum up the tax, it might be different than if the taxes are calculated for the item itself as each item round down but together it would round up and therefore 1 cent or so is different.

Maybe you always have to recalculate the tax or maybe there is a better solution.

**Comment by AndreasA** [comment]
@milan-kiener As feedback regarding tax fix. I think most cases will be fixed but also such special cases have to be taken into account

**Comment by milan-kiener** [comment]
@AndreasA at this point, the tax calculation/rounding for discounts is off compared to charges. We will take this up with Shopware.

**Comment by AndreasA** [comment]
The issue is with summing up the items. I think the sum method in Shopware should work differntly to fix this correctly.

**Comment by AndreasA** [comment]
@milan-kiener The issue is with summing up the items. I think the sum method in Shopware should work differntly to fix this correctly.
