### ISSUE TITLE
Error/Warning: DateTimeZone::__construct(): Unknown or bad timezone (1024)

### ISSUE THREAD

**Issue by AndreasA** [mollie/Shopware6#50]
As far as I know you have to instantiate DateTimeZone like this: `new DateTimeZone('UTC')`  as the constant provides an integer. I am not even sure why PHP has that constant as I don't know any place it can be used.

**Comment by milan-kiener** [comment]
@AndreasA Thanks for your feedback, it would be better to do it the way you suggest, indeed. A minor flaw we will fix in a future release.
