### ISSUE TITLE
Reduce amount of API Call when switching payment methods

### ISSUE THREAD

**Issue by fjbender** [mollie/Shopware6#507]
What is currently happening?

Whenever I switch payment methods in the frontend, the Mollie Profile and Methods APIs are called.

![image](https://user-images.githubusercontent.com/7370694/217791337-ac4faa75-351a-4010-9f3e-47e275e263df.png)

What should be happening?

The content of the API calls is fairly static and can safely be cached, at least within one checkout session. The API should not be called that often.

**Comment by boxblinkracer** [comment]
huch? that is not known :D 
nice finding, we should fix that

**Comment by fjbender** [comment]
This issue got worse after the POS payment method has been introduced. Now `/v2/methods/ideal` and `/v2/terminals` are called for every payment method selection screen, even when those payment methods are turned off.

**Comment by BlackScorp** [comment]
It is live now and we should have see less requests
