### ISSUE TITLE
Add help text for custom order number 

### ISSUE THREAD

**Issue by 4BRobby** [mollie/Shopware6#509]
It is necessary to have more information the syntax of the custom order number format in the configuration of the plugin.

A user might not be able to browse through the plugin src to find that {ordernumber} is the placeholder for the original Shopware order number in this field.

Found it in https://github.com/mollie/Shopware6/blob/master/src/Service/MollieApi/Builder/MollieOrderBuilder.php

So now I can configure it correctly.

**Comment by boxblinkracer** [comment]
Hi @4BRobby 

are we talking about this (see screenshot)?

im not quite sure why browsing through the source code should be required?
theres an instruction in below the textfield, as well as on the official user documentation page: https://github.com/mollie/Shopware6/wiki/Plugin-configuration

do you think this is still not enough? what would you add?

thank you

<img width="995" alt="Screenshot 2023-02-14 at 14 46 38" src="https://user-images.githubusercontent.com/5579326/218756534-0847f29b-968b-4be1-a024-f98455efcaec.png">

**Comment by 4BRobby** [comment]
> Hi @4BRobby
> 
> are we talking about this (see screenshot)?
> 
> im not quite sure why browsing through the source code should be required? theres an instruction in below the textfield, as well as on the official user documentation page: https://github.com/mollie/Shopware6/wiki/Plugin-configuration
> 
> do you think this is still not enough? what would you add?
> 
> thank you
> 
> <img alt="Screenshot 2023-02-14 at 14 46 38" width="995" src="https://user-images.githubusercontent.com/5579326/218756534-0847f29b-968b-4be1-a024-f98455efcaec.png">
My fault RTFM-style. But I am always interested in code, so I checked there.

Your screen shot looks like what the enduser might need.
With current version v3.4.0 there is no such helptext and preview:
![image](https://user-images.githubusercontent.com/22675949/218758419-7a6a51e7-f06d-4b71-b60a-91b31402f61b.png)

**Comment by boxblinkracer** [comment]
hi
no worries

aah...got it ...as soon as something is entered, the dialog is visible,...but you are right...its super fancy but not good for the UX :) ...i guess thats the problem

thanks for letting us know
this totally makes sense

if you find anything else, please write us, we do our best to create good guides and a good experience :)

**Comment by 4BRobby** [comment]
Yes I now see it, too. I have checked config.xml and the component.

My scenario was: MANY storefronts - so switching back and forth, checking configurations why the number came out on mollie like it did and the reason really might be. So of course the hint was not visible in this case for me :D

I am a developer, too - well and tend to complicate things sometimes from the end user point of view. But I am heavily using mollie and this was not the first input I wanted to give to have the best out of both points of view.

Thank you for taking care so fast. Much appreciated - and thanks for going over my RTFM point ;)

**Comment by boxblinkracer** [comment]
yeah, sometimes those things slip thru :)
and sure...really appreciate it, already changing the config....doesn take long and we release soon anyway :)

**Comment by 4BRobby** [comment]
Sorry I have to reopen.
When I switch to a certain storefron the hint does not show up (only if it was already visible on the default configuration but it will not update the preview).

When the number format configuration is linked to the default configuration (which is standard) and then unlinked the following JS error has just appeared - but only once:
'Cannot read properties of undefined (reading 'MolliePayments.config.molliePluginConfigSectionInfo')'

Hope this helps.

**Comment by boxblinkracer** [comment]
thank you
ill remove the hiding anyway and also check that

**Comment by boxblinkracer** [comment]
oh sorry, released with v 3.5
