### ISSUE TITLE
AsynchronousPaymentHandlerInterface::finalize has to throw unless payment was successful

### ISSUE THREAD

**Issue by TitanNano** [mollie/Shopware6#51]
Shopware expects a payment handler to throw an exception unless the payment was successfully completed.

https://github.com/shopware/platform/blob/c4abfdc17d4583d3efd76498be395f5ec376828d/src/Core/Checkout/Payment/Controller/PaymentController.php#L57-L71

https://github.com/shopware/platform/blob/76f02b4a332a244fd6dc29b01c658d1190572aad/src/Core/Checkout/Payment/PaymentService.php#L118-L160

Mollie currently only throws when the current payment status is either `STATUS_CANCELED` or `STATUS_FAILED`
https://github.com/mollie/Shopware6/blob/737261b14bbb6f93fa809409c6fa4f6893f3db43/src/Handler/PaymentHandler.php#L363-L366

It would be therefore better to always throw unless the status is `STATUS_PAID`.
```php
        if (
            isset($paymentStatus) && $paymentStatus !== PaymentStatus::STATUS_PAID
        ) {
```

We can provide a patch for this, if you'd like.

**Comment by milan-kiener** [comment]
Hi @TitanNano, it seems your feedback is about an old version. In the meantime, it is possible to enable or disable the standard failed payment redirect. If disabled, we use a custom route which triggers a retry before the payment gets a new status.
