### ISSUE TITLE
Error at payment

### ISSUE THREAD

**Issue by Tim-VL** [mollie/Shopware6#515]
Hi,
When a costumer is finishing payment I get an error in the log:

`Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET https://DOMEIN.nl/mollie/ideal/store-issuer/506a97822e9644f894552838f1b90f31/" (from "https://DOMAIN.nl/")" at /home/h100525/domains/DOMAIN.nl/public_html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 135 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): `

How can I fix this? I the Mollie log there are no errors.

Shopware 6.4.19.0

**Comment by boxblinkracer** [comment]
hi
this is weird,
this is actually an ajax request that happens when a dropdown is changed for iDeal and not even if the payment is submitted.
do you have any special setup with your storefront? or custom theme?

**Comment by Tim-VL** [comment]
Hi,
We use an purchased theme from the SW store, and that works fine. All plug-in are from the store as-well, so I dont expect any problem there. Store front works all fine.

**Comment by boxblinkracer** [comment]
could you reach out to us in the shopware support maybe? i think we should go with a zoom meeting.
do you know how to do that?

also, just to let you know...there's no guarantee that things from the store work.
from the description, i can only say that it sounds as if an ajax call is requested which is not done in the shopware standard across all versions that we test with :)
so i just want to let you know that your assumption is wrong...to not expect problems if you use things from the store.

in the end, i think it might be a combination with the theme. either we can improve something or the manufacturer of the theme....but we'll check that out in the zoom meeting, no worries, we'll get that done

:)

**Comment by Tim-VL** [comment]
Thanks for the response. 

Yes, will do that!

**Comment by Tim-VL** [comment]
Just tested... Yep error comes then the Ideal bank is selected.

**Comment by Tim-VL** [comment]
fixed for me with 3.6.0

**Comment by boxblinkracer** [comment]
oh nice
thanks for letting us know
great to hear @Tim-VL
