### ISSUE TITLE
PaymentStatusHelper::processPaymentStatus returns invalid status

### ISSUE THREAD

**Issue by TitanNano** [mollie/Shopware6#53]
In `PaymentHandler::finalize` mollie calls `PaymentStatusHelper::processPaymentStatus`, but because there is no status transition at this point, the method always returns `STATUS_OPEN`. This should actually return the current payment status and not `STATUS_OPEN`.

https://github.com/mollie/Shopware6/blob/737261b14bbb6f93fa809409c6fa4f6893f3db43/src/Helper/PaymentStatusHelper.php#L341

We can provide a patch for this, if you'd like.

**Comment by milan-kiener** [comment]
@TitanNano Your are giving feedback on a old version of the plugin. Therefore we can not reproduce this issue.
