### ISSUE TITLE
Use environment variables correct 

### ISSUE THREAD

**Issue by shyim** [mollie/Shopware6#534]
The plugin uses `getenv` to get the environment variable. This is totally wrong and the code should inject environment variables using DI with `%env(APP_URL)%` as example with an default set here

https://symfony.com/doc/current/configuration/env_var_processors.html

**Comment by boxblinkracer** [comment]
and i will of course check it out, no worries on that
it just changes the critical aspect on that if it is like this :)

**Comment by boxblinkracer** [comment]
aaaa theres the Admin Domain....that has been introduced once day,
ouch
thank you for helping on that :D

**Comment by boxblinkracer** [comment]
fixed in v3.6.0, thx for your help
