### ISSUE TITLE
Redirect URL max length (1023) reached

### ISSUE THREAD

**Issue by AndreasA** [mollie/Shopware6#54]
Hi,

our internal testing server has quite a long hostname, which results in the return URL to be too long as it contains the payment token (which contains the error and finish URL). 
I have now made a workaround by ensuring the error/success URLs are as short as possible but it would be better if this was not an issue at all.

I guess it might actually require a change in the Shopware system to avoid such long URLs but maybe you can get in touch with them. Or maybe you can improve tthe URL sent to mollie yourself too.

It probably is not that huge an issue as on production system the URL is usually not that long.

**Comment by milan-kiener** [comment]
This is on the Shopware side. We will pass this on, thanks for the feedback.
