### ISSUE TITLE
Status changed with latest update Plugin v1.3.6 

### ISSUE THREAD

**Issue by powolnymarcel** [mollie/Shopware6#55]
Hi,

With the latest update I get the order status being set to "completed" once someone has paid for an order, before the update the status was set to "open" and everything was good for us. Now we have trouble managing orders because the status is auto set to "completed".

Any idea why ?

Using  Plugin v1.3.6 
This is the mollie plugin conf :
https://i.ibb.co/x7xRbsd/2020-11-25-163747.png
https://i.ibb.co/B2zppJ3/2020-11-25-163705.png

**Comment by milan-kiener** [comment]
Hi Marcel, are you aware that you can manage the order states in the plugin configuration yourself?

**Comment by powolnymarcel** [comment]
You are so right ! I misunderstood the "order status" field. I'm so dumb :/ 

Thanks milan ;)
