### ISSUE TITLE
Whitespace in additional address line field cause error in url generation

### ISSUE THREAD

**Issue by ThLind** [mollie/Shopware6#57]
If a customer enters a whitespace in the additional address line field the url can't be generated. It's possible to fix it by an array map trim over billing and shipping address after building the orderData Array in PaymentHandler .

**Comment by milan-kiener** [comment]
@ThLind In which version of the plugin are you experiencing this issue?

**Comment by ThLind** [comment]
@milan-kiener It's Mollie Version 1.0.14 on Shopware Version 6.2.3

**Comment by milan-kiener** [comment]
@ThLind This issue should be allready resolved in the latest version, 1.3.6. Can you confirm that?
