### ISSUE TITLE
Cart validation error when creating an Apple Pay Direct order

### ISSUE THREAD

**Issue by michnhokn** [mollie/Shopware6#574]
When creating an order via Apple Pay direct, the service creates a guest customer and assigns the default salutation for the key `not_specified` because Apple Pay does not provide any salutation information. 
https://github.com/mollie/Shopware6/blob/master/src/Service/CustomerService.php#L427-L440

But because of the address cart validator the default salutation id is not a valid salutation id and the following error occurs:
```
Apple Pay Direct error when finishing payment: The cart is invalid, got 1 error(s). salutation-missing-profile: A salutation needs to be defined for the customer profile 2174216, Maria. (Session: ...) {"session":"","processors":{"uid":{"uid":"ae580ab"},"web":{"url":"/mollie/apple-pay/start-payment","ip":"109.250.172.0","http_method":"POST","server":"xxxx","referrer":"https://dev.koro.software/"},"introspection":{"file":null,"line":null,"class":"Kiener\\MolliePayments\\Controller\\Storefront\\ApplePayDirect\\ApplePayDirectController","callType":"->","function":"finishPayment"}}} []
```

https://github.com/shopware/platform/blob/v6.4.20.1/src/Core/Checkout/Cart/Address/AddressValidator.php#L109-L112
It looks like this is just an error with Shopware 6.4.X the RC6.5.X no longer checks against the `Defaults::SALUTATION`.

Is there a smart way to fix this?

**Comment by boxblinkracer** [comment]
Hi there
sorry for the late reply

just fixed it for the upcoming version
thank you
