### ISSUE TITLE
Not working on Shopware 6.5

### ISSUE THREAD

**Issue by drieken** [mollie/Shopware6#576]
I can't enable the plugin on Shopware 6.5 because it's not supportet yet.

**Comment by boxblinkracer** [comment]
Hi 

thank you for your message
yes, it's not available at the moment

we are working really really hard since a while on it,
and are (hopefully) almost at the end now, 
then we start a more intense testing phase and release it

**Comment by drieken** [comment]
Great to hear!

**Comment by Tim-VL** [comment]
Hi @boxblinkracer, any updates?

**Comment by weiterfunken** [comment]
Hey @boxblinkracer , any updates for 6.5? Our Clients still waiting :-(

**Comment by boxblinkracer** [comment]
hi. yes
so latest master is working. 
we are already in the testing phase and test everything in 6.4 and 6.5. so should be released very soon :)

**Comment by weiterfunken** [comment]
@boxblinkracer perfect :-)

**Comment by AndreasA** [comment]
@boxblinkracer Any news regarding a 6.5 supported release ?

**Comment by BlackScorp** [comment]
hi @AndreasA , @weiterfunken @Tim-VL @drieken 

we have released the new version today, now the plugin works with shopware 6.5.

**Comment by TanjaBayer** [comment]
I installed the new version of the plugin (4.0), and when doing the upgrade it says compatible

But when upgrading to 6.5.0.0 the upgrade fails with the following error leaving the shop in a broken state. Any ideas?
```
PHP Fatal error:  Class Kiener\MolliePayments\Compatibility\Bundles\FlowBuilder\Actions\ShipOrderAction contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Shopware\Core\Content\Flow\Dispatching\Action\FlowAction::handleFlow) in /sw6/vendor/store.shopware.com/molliepayments/src/Compatibility/Bundles/FlowBuilder/Actions/ShipOrderAction.php on line 14
Symfony\Component\ErrorHandler\Error\FatalError {
#12400
  #message: "Error: Class Kiener\MolliePayments\Compatibility\Bundles\FlowBuilder\Actions\ShipOrderAction contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Shopware\Core\Content\Flow\Dispatching\Action\FlowAction::handleFlow)"
  #code: 0
  #file: "/sw6/vendor/store.shopware.com/molliepayments/src/Compatibility/Bundles/FlowBuilder/Actions/ShipOrderAction.php"
  #line: 14
  -error: array:4 [
    "type" => 1
    "message" => "Class Kiener\MolliePayments\Compatibility\Bundles\FlowBuilder\Actions\ShipOrderAction contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Shopware\Core\Content\Flow\Dispatching\Action\FlowAction::handleFlow)"
    "file" => "/sw6/vendor/store.shopware.com/molliepayments/src/Compatibility/Bundles/FlowBuilder/Actions/ShipOrderAction.php"
    "line" => 14
  ]
}
```

**Comment by boxblinkracer** [comment]
Hi there

huch....thats totally weird, we even have cypress tests in there...
and its been manually tested (like really all tests that we have have been manually tested in 6.4 and 6.5, 200 to 300 e2e tests)

wondering if this is only in the upgrade phase. how do you do the upgrade? CLI or admin?
the error just says that the code is wrong...but thats completely weird.
would you mind trying it in a fresh installation, just to see if anything is weird on your side?

do you know dockware? 
"docker run --rm -p 80:80 -p 443:443 dockware/dev:6.5.0.0"
that runs a fresh shopware 6.5

thank you

**Comment by TanjaBayer** [comment]
I did the upgrade via the admin ui.
* I did try to upgrade to different versions 6.5.0.0 and also 6.5.2.1 but with same result
* Currently I started a new try uninstall mollie before the upgrade, do the upgrade and than I will try to install mollie again, but I assume, that should not be necessary, its not yet finished but I will report once it is

> docker run --rm -p 80:80 -p 443:443 dockware/dev:6.5.0.0
and than doing a mollie install you mean?

**Comment by boxblinkracer** [comment]
thanks for the feedback,
ok so when its also in the new shopware version, then it might really be an upgrade problem (like a race condition) or caching stuff....phu...

uninstalling seems like a good solution, although annoying

yes, the docker line is just for testing...just upload the zip in the admin for testing and see if it works 

please let me know what happens, thanks

**Comment by AndreasA** [comment]
@TanjaBayer Did you check your PHP version? I remember running into a similar issue when switching to dev-master, but I accidentally used the forgot to change the PHP version in my Docker container (which was still 7.4). Shopware 6.5+ only supports PHP 8.1 or 8.2

**Comment by AndreasA** [comment]
@TanjaBayer 
- Have you tried to remove everything inside the `var/cache` folder manually before starting the upgrade to 6.5?
If I remember things correctly, Shopware creates a separate cache folder according to version/installed plugins in there. It might be that an outdated folder is used during the update. If so, it might actually be a Shopware issue, 
e.g. one with an older mollie version active where the action did not yet implement the necessary methods.
- From which Shopware 6.4 version exactly do you try to upgrade? Might be relevant as well. Maybe the issue occurs if one updates from before 6.4.6.0 as there is some change regarding loaded flow actions.

**Comment by TanjaBayer** [comment]
@AndreasA 
* No I did not remove the stuff in the folder, I do not have direct access at the moment in there, that is also why I started the upgrade via the admin ui and not the cli, but It might be worth giving it a try if my current approach will also fail
* I upgraded from the latest 6.4 version which if i remember correctly was 6.4.20.2

**Comment by AndreasA** [comment]
@TanjaBayer One last question - though probably not a solution - but from your comment above the plugin code used that produces the failure is in `/sw6/vendor/store.shopware.com/molliepayments/`.

Did you originally install the plugin using composer? If so, I am acutally not sure what happens if a plugin update is started in the administration as I think Shopware installs plugin updates  (if installed through the administration) to `custom/plugins`. 
However, It is possible that the class autoloading, still loads various files from the old folder in that scenario. But you would need to check the classloader config of composer and custom/plugins folder on the server to verify. In that case it is probably a Shopware bug that this is even possible 😄 

Otherwise it could still be an opcache/realpath issue.

**Comment by TanjaBayer** [comment]
> Did you originally install the plugin using composer

Yes that is how it was installed.

Btw. upgrade with uninstall/reinstall of the mollie extension worked in the dev environment so I guess I will go this way.

**Comment by boxblinkracer** [comment]
hi all, and thanks @AndreasA for your great input :)
i guess the most efficient way to get you going is, that you uninstall/reinstall as you just mentioned with the dev environment.
can you post if it worked in here (once you do it on production)

i would then make sure shopware is notified about this thread, maybe they can give some input too, or even discover anything wrong in shopware

**Comment by AndreasA** [comment]
> Btw. upgrade with uninstall/reinstall of the mollie extension worked in the dev environment so I guess I will go this way.

good to hear. Maybe a info on the store page could potentially help others.

> Yes that is how it was installed. But the updates of the plugins are also done via cli during the build/startup phase. Only the shopware update itself is done via UI

Ah. OK. Then this shouldn't be an issue. Though I have never done a Shopware update using the UI, so I have no idea what might go wrong there. But I guess some kind of caching issue is still the most likely scenario, be it that a stale Symfony cache is used during the upgrade, or maybe opcache etc. related.

**Comment by TanjaBayer** [comment]
Hi @boxblinkracer @AndreasA thanks for your fast feedback. I will give an update once we do the upgrade on the other environments, however as another plugin is at the moment blocking the upgrade I can not tell when that will be.

**Comment by boxblinkracer** [comment]
ok shopware told me, it might be due to the opcache

**Comment by boxblinkracer** [comment]
so we have a lot of positive feedback on 6.5 by now
i hope its ok that i close this issue

feel free to open a new one or this one again :) 
thank you
