### ISSUE TITLE
Wrong type hint used in \Kiener\MolliePayments\Service\OrderService - EntityRepository instead of EntityRepositoryInterface

### ISSUE THREAD

**Issue by AndreasA** [mollie/Shopware6#58]
In order to support EntityRepository decoration like e.g. Shopware does internally for some of there repositories, you should use EntityRepositoryInterface instead of EntityRepository.

It provides all the same methods.

current code:

```
    public function __construct(
        EntityRepository $orderRepository,
        EntityRepository $orderLineItemRepository,
        LoggerInterface $logger
    )
    {
        $this->orderRepository = $orderRepository;
        $this->orderLineItemRepository = $orderLineItemRepository;
        $this->logger = $logger;
    }
```

I had to decorate the repository in a project and now this fails.

**Comment by milan-kiener** [comment]
@AndreasA you are correct. Thanks for your feedback. We will replace this in an upcoming release.

**Comment by milan-kiener** [comment]
@AndreasA This will be fixed in the release of this week.

**Comment by AndreasA** [comment]
Thanks 👍
