### ISSUE TITLE
Update mollie/mollie-api-php to latest version - any reason why it is still 2.40.1 (over a year old)?

### ISSUE THREAD

**Issue by AndreasA** [mollie/Shopware6#585]
Just wondering if the mollie/mollie-api-php dependency is limited to 2.40.1 for a reason. It should at least allow patch level versions I think which would be 2.40.2. 

However, if you want to use a fixed version to ensure a specific version is always used, there is still the question why 2.40.1 is still used. That version is from January 2022.

**Comment by boxblinkracer** [comment]
hi
yes easy answer, there was a) no need, and b) this was the time when they dropped php support for version xy which we still needed, thats why its also locked to that version, even without lock file...just feels safer....(something like that, cannot fully remember)

so theres no downside at the moment or in general
but what a coincidence...we just recently discussed, that its time for another update of this too (and now with min support of shopware 6.4.x also the php min versions might be easier :)

hope this explains it

**Comment by boxblinkracer** [comment]
updated in 4.2.0 :)
