### ISSUE TITLE
Promo code ERROR + free orders ?

### ISSUE THREAD

**Issue by powolnymarcel** [mollie/Shopware6#59]
Hello,

We have created a promo code : "testcode" value = 25€
We tested an order, we bought an item that cost 10€ and applied the promo code
Cart total is 0€

the following error occurs:

`Could not create a Mollie Payment Url, error: Could not create Mollie order, error: [2020-12-02T20:41:37+0000] Error executing API call (422: Unprocessable Entity): The amount is lower than the minimum. Field: payment.amount. Documentation: https://docs.mollie.com/reference/v2/orders-api/create-order`

**Comment by milan-kiener** [comment]
Hi @powolnymarcel At best, you should provide a separate payment method for this and use a business rule to rule out Mollie payment methods in this case. It's not logical to send a 0€ order to Mollie.

**Comment by powolnymarcel** [comment]
Ok I understand that, I read the Mollie doc and min value is 0.01cents.

I have set up a rule but I have "Credit card" as the default payment mean. If the cart total is 0€, how could I auto switch to free payment ?
