### ISSUE TITLE
UpdatePayment for subscription leads to API Exception "The amount is lower than the minimum" because of amount 0.00

### ISSUE THREAD

**Issue by philipschikora** [mollie/Shopware6#590]
If we try to update a payment method for a subscription the payload includes an amount of 0.00 which is rejected with the error message: "The amount is lower than the minimum".
Version 3.6

**Comment by boxblinkracer** [comment]
Hi there
ok that is weird
because for subscription updates the amount of 0,00 is ok. i did also test this
maybe the mollie api has changed or had an issue

could you probably give me a step by step instruction on what you did?
that would help

thank you
