### ISSUE TITLE
Apple Pay Direct missing address data

### ISSUE THREAD

**Issue by michnhokn** [mollie/Shopware6#595]
Some customers ordering via apple pay direct do not have the complete shipping address.

I looked into this and it turns out apple provides an array of address lines to the `onpaymentauthorized` event and also [warns about the format in the documentation](https://developer.apple.com/documentation/apple_pay_on_the_web/applepaypayment/1916097-shippingcontact#:~:text=Note,you%20use%20it.).

The mollie plugin only gets the first line of this array ...
https://github.com/mollie/Shopware6/blob/2a150714e0bf8b5d0769483157539e99f2de94d0/src/Resources/app/storefront/src/mollie-payments/plugins/apple-pay-direct.plugin.js#L345
... to use it in the controller later.
https://github.com/mollie/Shopware6/blob/2a150714e0bf8b5d0769483157539e99f2de94d0/src/Controller/Storefront/ApplePayDirect/ApplePayDirectControllerBase.php#L346

It would be nice to also transfer possible other lines as additional address lines in the shopware address format so the information is not missing when shipping the orders.

**Comment by michnhokn** [comment]
@boxblinkracer Just want to push this a little. We currently have many support tickets because of thath.

**Comment by boxblinkracer** [comment]
oh ok
lets slack? then i can tackle it :)
because i need some more understanding regarding test data
