### ISSUE TITLE
Mollie limits got not applied

### ISSUE THREAD

**Issue by rommelfreddy** [mollie/Shopware6#596]
the customer is using
- Shopware 6.5.3.1 
- latest Mollie extension

If the shop is in prod-env the Mollie limits got not applied. 
It got only applied one times and after that the the payment-method route loading the payment-methods only from the cache. 

Is this a known issue?
Did I do something wrong?

**Comment by boxblinkracer** [comment]
Hi there
this is not known and has been tested
can you provide a step by step instruction please?
maybe you have another way and found a bug :)

**Comment by boxblinkracer** [comment]
Hi
just wanted to ask if you have any updates on this

**Comment by BlackScorp** [comment]
@rommelfreddy so the problem with the mollie limits were because of shopware cache, it is fixed now with 4.5.0
