### ISSUE TITLE
The api keys wont load

### ISSUE THREAD

**Issue by coudenysj** [mollie/Shopware6#6]
I get a PHP error when I want to pay my cart:

`[2020-04-02 15:26:32] request.CRITICAL: Uncaught PHP Exception TypeError: "Return value of Kiener\MolliePayments\Setting\MollieSettingStruct::getTestApiKey() must be of the type string, null returned" at /var/www/custom/plugins/MolliePayments/src/Setting/MollieSettingStruct.php line 47 {"exception":"[object] (TypeError(code: 0): Return value of Kiener\\MolliePayments\\Setting\\MollieSettingStruct::getTestApiKey() must be of the type string, null returned at /var/www/custom/plugins/MolliePayments/src/Setting/MollieSettingStruct.php:47)"} []`

I've entered both keys on the /admin#/sw/plugin/settings/MolliePayments page.

Am I doing somthing wrong?

**Comment by peter-bztrs** [comment]
I can confirm that this is also occuring in our setup.
Shopware 6.1.5

**Comment by coudenysj** [comment]
It broke due to this commit: https://github.com/mollie/Shopware6/commit/0321b296b912874ae8714b2a19d0b0e85e278868#diff-4d4c2f990fa8293eb30b3d45a5c1b91eR78.

The sales_channel_id is empty by default.

**Comment by KienerNL** [comment]
The sales channel id can be null in the current release. Thanks for the input 😊

**Comment by alexbaat** [comment]
I still have this problem in 1.0.7 in case I don't explicit set the settings for the specific sales channel.
