### ISSUE TITLE
Bank Data in Order Confirmation Mail

### ISSUE THREAD

**Issue by hensmatt** [mollie/Shopware6#609]
In the Mollie Shopware 5 plugin there was the option to integrate the bank data into the order confirmation mail. The following code does not work in the Shopware 6 version.

{if $Mollie.bank.exists}
   {$Mollie.bank.name}<br />
   {$Mollie.bank.account}<br />
   {$Mollie.bank.bic}<br />
   {$Mollie.bank.reference}<br />
{/if}

**Comment by boxblinkracer** [comment]
Hi

thank you for this
you are right, this is indeed (as far as I know) not yet implemented in Shopware 6

I'll see what I can do :)

thank you for this

**Comment by hensmatt** [comment]
Hello Christian,

Is it already clear whether the feature can be implemented and when?

Best regards
Matthias

**Comment by BlackScorp** [comment]
Hello @hensmatt 

this feature is not that easy to implement in Shopware 6 since we cannot add custom variables into Mail Templates. How ever i will try to find a workaround over order.extension or order.customFields and we goging to add this into wiki when its released.

Sorry for the inconvenience

**Comment by BlackScorp** [comment]
@hensmatt 

sorry to inform you, but it is not possible to add additional mollie data into order confirmation mail. Shopware sends the Confirmation Mail before the payment provider can add his own logic. so at the time when the confirmation mail is sent, there is currently no mollie order created and therefore we dont have any data.

when the payment is completed i added the bank information to the order.customFields.mollie_payments. This way you can at least add those information into invoice mail template or output it checkout finish page with your own template.

i hope this helps, that is all i can do here
