### ISSUE TITLE
 HTTP 500 after cancel payment

### ISSUE THREAD

**Issue by powolnymarcel** [mollie/Shopware6#61]
Hello,

A customer has send us this screenshot. Anything related to Mollie ?

He tried to pay and didn't have enough on his bank account which triggered this :

https://i.ibb.co/c82jWhx/Capture-d-cran-2020-12-15-121321.png

**Comment by milan-kiener** [comment]
Hi @powolnymarcel , I can't open the screenshot.

**Comment by powolnymarcel** [comment]
I have just tried the link and it's working

**Comment by milan-kiener** [comment]
@powolnymarcel Now the screenshot works. This seems to be related to your Shopware installation. Have you maybe added extra order statuses? Or maybe a plugin that does?
