### ISSUE TITLE
Plugin not compatible with shopware 6.3

### ISSUE THREAD

**Issue by Ahmedazeem98** [mollie/Shopware6#613]
Due to load route files function (**configureRoutes**) in main class the plugin not compatible with all 6.3 versions

**Comment by boxblinkracer** [comment]
Hi 

thank you for your answer
yes the latest versions of the plugin are not compatible with Shopware 6.3.x anymore
we had to set the minimum version to 6.4

This was unfortuantely necessary in combination with the Shopware 6.5 support

**Comment by boxblinkracer** [comment]
Hi

i think i can close this ticket now?
otherwise feel free to open it again :)
