### ISSUE TITLE
StockManager should respect the shopware configuration of stock management

### ISSUE THREAD

**Issue by niklaswolf** [mollie/Shopware6#622]
Since Shopware 6.5 it is possible to disable Shopware's stock calculation:

https://github.com/shopware/platform/blob/trunk/UPGRADE-6.5.md#6550 
https://docs.shopware.com/en/shopware-6-en/tutorials-and-faq/howto/disable-stock-calculation

I think the Mollie plugin should respect those settings in `\Kiener\MolliePayments\Service\Stock\StockManager::increaseStock` to not have unexpected behaviour :)

**Comment by BlackScorp** [comment]
Hi Thanks for pointing it out.

iam going to add fix this

**Comment by niklaswolf** [comment]
Without further thought I'd spontanously say that inside the increaseStock method there should be a check for the configuration of the stock manager (enabled/disabled). If it's disabled, the increaseStock method should do nothing.
Like this the configuration is taken into account that is set in the moment the refund manager is used. This is what I'd expect as a user, because this is also how Shopware would handle it itself.
