### ISSUE TITLE
error on route

### ISSUE THREAD

**Issue by Tim-VL** [mollie/Shopware6#636]
Hi,

I'm getting this error in my log, no payment was made.

![afbeelding](https://github.com/mollie/Shopware6/assets/75847795/238fcc4e-cbae-4359-9b2b-0745e9a348c3)

Any suggestions?

**Comment by boxblinkracer** [comment]
Hi

are you using the store-api or storefront
there should be a url /mollie/ideal/store-issuer/xxx/yyy available as GET in the storefront

if its not reachable, can you try to clear your caches?

thanks you

**Comment by Tim-VL** [comment]
It's just the plugin that i'm using. This message comes from the front-end, order by costumer that did not work.

**Comment by boxblinkracer** [comment]
Hi

ah, this is just a cosmetic error, doesnt have any impact
only happens if the user switches to the dropdown issuer "no issuer" (or when its initially loaded on that page)

it has been fixed for the upcoming version :)

**Comment by BlackScorp** [comment]
was fixed in newest version
