### ISSUE TITLE
Errors during the update Mollie plugin from 3.6.0 to 4.2.0

### ISSUE THREAD

**Issue by stepan-twnty** [mollie/Shopware6#639]
Hi

During the update Mollie plugin from 3.6.0 to 4.2.0 I've gotten a few errors:

1. ```Uncaught PHP Exception Twig\Error\LoaderError: "The "/home/USER/shopware/custom/plugins/MolliePayments/src/Resources/views/../app/storefront/dist" directory does not exist ("/home/USER/shopware/custom/plugins/MolliePayments/src/Resources/views/../app/storefront/dist")." at /home/USER/shopware/vendor/twig/twig/src/Loader/FilesystemLoader.php line 92 {"exception":"[object] (Twig\\Error\\LoaderError(code: 0): The \"/home/USER/shopware/custom/plugins/MolliePayments/src/Resources/views/../app/storefront/dist\" directory does not exist (\"/home/USER/shopware/custom/plugins/MolliePayments/src/Resources/views/../app/storefront/dist\"). at /home/USER/shopware/vendor/twig/twig/src/Loader/FilesystemLoader.php:92)"} []```
2. Uncaught Error: Kiener\MolliePayments\Service\SettingsService::__construct(): Argument #2 ($repoSalesChannels) must be of type Kiener\MolliePayments\Repository\SalesChannel\SalesChannelRepositoryInterface, Shopware\Core\Framework\DataAbstractionLayer\EntityRepositoryForwardCompatibilityDecorator given, called in /home/USER/shopware/var/cache/prod_hb3c7d0e489e901531ea9110f97323125/ContainerXdgwtmJ/Shopware_Core_KernelProdContainer.php on line 34049 {"exception":"[object] (TypeError(code: 0): Kiener\\MolliePayments\\Service\\SettingsService::__construct(): Argument #2 ($repoSalesChannels) must be of type Kiener\\MolliePayments\\Repository\\SalesChannel\\SalesChannelRepositoryInterface, Shopware\\Core\\Framework\\DataAbstractionLayer\\EntityRepositoryForwardCompatibilityDecorator given, called in /home/USER/shopware/var/cache/prod_hb3c7d0e489e901531ea9110f97323125/ContainerXdgwtmJ/Shopware_Core_KernelProdContainer.php on line 34049 at /home/USER/shopware/custom/plugins/MolliePayments/src/Service/SettingsService.php:55)"} []

Mollie still working but I want to be sure that all is okay from the dev side and that I don't need to do any additional stuff (for example the error might break smth and I need to reinstall the plugin)

Shopware 6.4.20.0.
Front-end headless.

**Comment by boxblinkracer** [comment]
hi there

thank you for your message
phu...these are a few updates....mhm...
so let me focus on the errors what they mean

1) i think thats fine, but i have never seen the error
here is an explanation about that file: https://github.com/mollie/Shopware6/wiki/Dev-Artifacts
can you double check for me

2) i think thats only a cache thing, we have made our own interfaces, and it looks as if the cached services still have another type...so maybe clear caches and it should be gone

i hoep this helps you
