### ISSUE TITLE
Admin build fails

### ISSUE THREAD

**Issue by MelvinAchterhuis** [mollie/Shopware6#658]
Version 4.1.0+

`SyntaxError: /vendor/store.shopware.com/molliepayments/src/Resources/app/administration/src/module/mollie-payments/components/mollie-pluginconfig-section-order-lifetime-warning/services/OderLifeTimeLimitDetectorService.js: Support for the experimental syntax 'classProperties' isn't currently enabled (2:32):`

```
      1 | export default class OrderLifeTimeLimitsDetector {
    > 2 |     maximumOrderLifeTimeKlarna = 28;
        |                                ^
      3 |     maximumOrderLifeTime = 100;
      4 |
      5 |     isOderLifeTimeLimitReached(orderLifeTime) {
```

**Comment by boxblinkracer** [comment]
Hi Melvin

oh ouch, yeah thats wrong, that should be done in the constructor

thanks a lot

i will create a fix :)
