### ISSUE TITLE
Mollie subscription missing ES-indexer for administration

### ISSUE THREAD

**Issue by niklaswolf** [mollie/Shopware6#670]
If you enable Elasticsearch/Opensearch for the administration, the search in the dasboard/homepage of the admin is broken.
This is caused by a missing ES-indexer for the entity `mollie_subscription` here:
```
\Shopware\Elasticsearch\Admin\AdminSearchRegistry::getIndexer
```

To enable ES for admin:
```
ADMIN_OPENSEARCH_URL="XYZ"
SHOPWARE_ADMIN_ES_ENABLED=1
SHOPWARE_ADMIN_ES_REFRESH_INDICES=1
SHOPWARE_ADMIN_ES_INDEX_PREFIX=sw-admin
```

<details>
<summary>Full callstack here</summary>

Noticed exception 'Shopware\Elasticsearch\Exception\ElasticsearchIndexingException' with message 'Following errors occurred while indexing: 
' in vendor/shopware/elasticsearch/Admin/AdminSearchRegistry.php:175

in Shopware\Elasticsearch\Admin\AdminSearchRegistry::getIndexer called at vendor/shopware/elasticsearch/Admin/AdminSearcher.php (51)
 in Shopware\Elasticsearch\Admin\AdminSearcher::search called at vendor/shopware/elasticsearch/Admin/AdminSearchController.php (47)
 in Shopware\Elasticsearch\Admin\AdminSearchController::elastic called at vendor/symfony/http-kernel/HttpKernel.php (181)
 in Symfony\Component\HttpKernel\HttpKernel::handleRaw called at vendor/symfony/http-kernel/HttpKernel.php (76)
 in Symfony\Component\HttpKernel\HttpKernel::handle called at vendor/symfony/http-kernel/Kernel.php (197)
 in Symfony\Component\HttpKernel\Kernel::handle called at vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php (86)
 in Symfony\Component\HttpKernel\HttpCache\SubRequestHandler::handle called at vendor/symfony/http-kernel/HttpCache/HttpCache.php (473)
 in Symfony\Component\HttpKernel\HttpCache\HttpCache::forward called at vendor/symfony/http-kernel/HttpCache/HttpCache.php (273)
 in Symfony\Component\HttpKernel\HttpCache\HttpCache::pass called at vendor/symfony/http-kernel/HttpCache/HttpCache.php (287)
 in Symfony\Component\HttpKernel\HttpCache\HttpCache::invalidate called at vendor/symfony/http-kernel/HttpCache/HttpCache.php (210)
 in Symfony\Component\HttpKernel\HttpCache\HttpCache::handle called at vendor/shopware/core/HttpKernel.php (143)
 in Shopware\Core\HttpKernel::doHandle called at vendor/shopware/core/HttpKernel.php (65)
 in Shopware\Core\HttpKernel::handle called at public/index.php (71)
 in Symfony\Component\HttpKernel\HttpKernelInterface@anonymous
 in Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner::run called at vendor/autoload_runtime.php (29)
 in require_once called at public/index.php (14)

</details>

**Comment by bojandavkov** [comment]
Does the vendor plan to fix this? this is still an issue while searching in the admin.

**Comment by BlackScorp** [comment]
@bojandavkov @niklaswolf yes iam currently working on it. in newest shopware version it works, it seems like shopware catches the error. have to check 6.5 and 6.4

**Comment by BlackScorp** [comment]
@bojandavkov @niklaswolf 
i merged the changes,can you download the ZIP file from this action when its done https://github.com/mollie/Shopware6/actions/runs/9808095159

and then try out on your setups?

**Comment by bojandavkov** [comment]
@BlackScorp How can i download the ZIP file from the action?
