### ISSUE TITLE
Missing null checks lead to breaking JS Code in Safari

### ISSUE THREAD

**Issue by ireznik** [mollie/Shopware6#70]
While debugging I stumbled upon this code
https://github.com/mollie/Shopware6/blob/a0a7e1b25211acdc0770d7fc55a202117d3cd7f7/src/Resources/app/storefront/src/mollie-payments/plugins/creditcard-components.plugin.js#L25

A missing check on the options generates the following **error** ~~warning~~:
TypeError: null is not an object (evaluating 'this.options.shopUrl.substr')
A simple null check resolves the issue but I would assume there are more such missing checks

**Comment by ireznik** [comment]
Thanks for the response @schmitzcarsten. It is actually an error which breaks the application and not a warning.

**Comment by schmitzcarsten** [comment]
@ireznik ok priority just increased. We have a look soon

**Comment by schmitzcarsten** [comment]
next release will fix this issue
We are planning release on Wednesday
