### ISSUE TITLE
[QUESTION] Tax now fixed in mollie plugin ?

### ISSUE THREAD

**Issue by AndreasA** [mollie/Shopware6#72]
I just saw that you merged a PR that fixes the tax calculation by doing it as mollie expects it to for mollie API. 

Does this now fix all tax related issues? And if so, I thought you wanted to have this fixed in the Shopware core, was there a reason against it?

By doing this I guess using AvaTax would also work correctly as you will recalculate the taxes according to the mollie?

When can we expect an official release with this fix?

**Comment by AndreasA** [comment]
I also added on comment to the merged commit:
https://github.com/mollie/Shopware6/commit/3afbf7730d36d79c85ef10ec85fc2083144be24e#r47026188

**Comment by AndreasA** [comment]
Some further questions regarding tax caluclation:
https://github.com/mollie/Shopware6/commit/3afbf7730d36d79c85ef10ec85fc2083144be24e#diff-630924269304a2416293cdd4e6de58d4fbfb1e5f75d00f397491229f2c815d50R409

Why only if the calculated tax is not the same as the calculated gross price? That would mean we have a taxation of 100% which is kind of unlikely?
Don't you want to check againt the order line item amount to determine the full amount was taxed?

And here https://github.com/mollie/Shopware6/commit/3afbf7730d36d79c85ef10ec85fc2083144be24e#diff-630924269304a2416293cdd4e6de58d4fbfb1e5f75d00f397491229f2c815d50R415

I think you should first do the `* 100` and then round with 2 decimals because otherwise it is possible to have floating point imprecisions.

**Comment by boxblinkracer** [comment]
hi

there is a reason for this. 
shopware calculates hoizontal and vertical taxes depending on the config. 

also sometimes the values make problems with rounding

mollie only supports one tax calculation and is very strict with the values
this is for the orders api on line item level

the only way to bring payments through in edge cases is to use the correct rounding and algorithm

also this is not the total amount itself but for cross checks. 

it shouldnt create wrong capture values. if you find a case let us know please

im not deeply involved in mollie sw6 but in 5 where also rounding problems had to be solved

cheers
christian

**Comment by AndreasA** [comment]
@boxblinkracer 
I am fine with it being fixed in the plugin and to send different taxes to mollie.

However, the line I referenced, changes the unit line item price (`$unitPrice *= ((100 + $vatRate) / 100);`). Isn't mollie's total calculated from those? Or is the total provided separately?

If so, wouldn't mollie also throw an error as the expected total does not match?

Personally, I am a actually surpsied they do those checks as I think the payment provider really should not care about the tax calculation but use the same one as provided by the shop but that is an altogether different issue 😄

**Comment by boxblinkracer** [comment]
i think that looks like converting from net to gross price

that also in sw5

im on the phone now. well check it out tomorrow at work on the desktop screen :)

**Comment by schmitzcarsten** [comment]
Yes with Shopware 6.3.5 there is a fix for the calculation of tax amounts for promotion lineItems. My tests with this version showed that now same vat amounts in shopware and in mollie are calculated in certain edge cases. 

But: All merchants with pre 6.3.5 shopware also need a fix. 
And: There are different tax calculation ways (horizontal and vertical calculation) which lead to different tax amounts in edge cases.
We have to address the problem like the mollie api awaits that tax calculation is done.  
So we decided to take the gross prices from shopware (this is what the customer has to pay) and recalculate the tax amounts for each lineitem that has to be given to mollie api with the mollie api algorithm.

I added a comment in your PR statement to point out why the unit price has to be calculated with net price configuration

**Comment by AndreasA** [comment]
@boxblinkracer @schmitzcarsten Ah yes, I re-checked the code and after explanation it makes sense.
One final question though: mollie does not have a problem with `unitPrice * quantity != orderlineItemPriceWithTax`?  Because due to this calculation this could happen I guess - didn't check the whole code.

Actually I am fine with adding it, I just mentioned it as there were two previous tax related issues that were closed as Shopware was supposed to fix it, see https://github.com/mollie/Shopware6/issues/49 and https://github.com/mollie/Shopware6/issues/28

However, I think ensuring the values are correct before sending it to mollie is the better solution anyway because in theory there could be a lot of different ways taxes are calculated (e.g. third party plugins) that might otherwise fail it. 

So I am all for this being in the plugin. I was just wondering.

**Comment by AndreasA** [comment]
Ah sorry, Of course, the order line item total can be different to unitPrice * quantity. After all that is to be expeced with horizontal tax calculation 😄

**Comment by AndreasA** [comment]
One last question. With your fix, if I were to implement e.g. Avalara AvaTax for US tax calculation which is quite tricky, it would still work as you prepare the taxes as Avalra needs them, correct?

**Comment by AndreasA** [comment]
Some last question - probably just an error from my understanding but in this part of the tax code (not the changes):
https://github.com/mollie/Shopware6/blob/master/src/Service/OrderService.php#L409

Why is that line there? what is it supposed to check because it looks like it checks the calculated tax against the price for which the tax was calculated and those should nearly always be different ?

**Comment by AndreasA** [comment]
@schmitzcarsten 
Ah and thanks for your effort in getting this fixed. As mentioned personally I think it is weird that mollie actually does those checks as various countries do tax calculations differently, there is no universal way to do it for all.

**Comment by schmitzcarsten** [comment]
@AndreasA As I do not know AvaTax I may only give limited answers for this. If AvaTax manipulates the orderLineItems for tax calculation, than there may be a problem because calculation is done via the orderLineItems. As long the taxes (rates) and gross prices keep correct in the orderLineItem, this should work without any problems.

line 409:
The TaxCollection is a collection and therefore there may be different tax rates for one item (think about a promotion that discounts of a 7% and a 19% product). To get this in a correct way for calculation a mixed taxrate is calculated because mollie api may only accept one tax rate for an item. In line 409 there is only a check if price and tax are not equal and if so the mixed tax rate is calculated. But to be honest, there could not be any circumstance where tax amunt and price are equal because tax amount is percentage of price. It is used legacy code. We have to refactor some code step by step 

The release is planned for next Monday (planned revision tag 1.3.12)

**Comment by AndreasA** [comment]
Hi @schmitzcarsten I know that it is done due to multiple tax rates which makes sense and those can happen more often than one might expect (AvaTax). 
However, I just meant that the check in line 409 does not make any sense. You should just calculate it, if their is more than one tax rate I guess but from what you said you will adjust this anyway.

Regarding AvaTax, there is currently no plugin available. However, where I work we implemented it for Shopware6 for one of our customers. Their API basically returns tax amount and tax rates per line item which we then store per line item.

The prices themselves are shown as net as the tax is only calculated at the end and added to the net taxes. We adjust the calculated taxes and the tax rates. So I guess it would work? Not an issue yet, as none of our customer uses mollie and AvaTax so far but it would be nice to know if it works. The gross/net prices would of course have been adjusted too. 

One issue might be that AvaTax might have the same tax rate for the same line item twice. In order to fix this, I created a child line item that has the second tax rate. However, that should be propogated to the parent correctly too I guess?

I guess I could try to install it in our test setup for that one customer.

**Comment by AndreasA** [comment]
P.S. you can close the issue, after your answer to the last question regarding AvaTax 😄

**Comment by schmitzcarsten** [comment]
We get the orderlineitems from shopware. If this lineitem is correctly prepared regarding prices and taxes (gross / net price configuration of customer), then it will be calculated correctly. Even if there is the same tax rate more than one time it should be no issue because we would recalculate taxrate by price tax amount in these cases.
