### ISSUE TITLE
Custom line item types support

### ISSUE THREAD

**Issue by AndreasA** [mollie/Shopware6#73]
Hi, 

it would be nice if custom line item types were support. I know it will not be necessary in most cases as those are usually used as child line items which you do not need/use for mollie payments anyway.
However, in case it is ever necessary that would be really great.

The easiest solution would be to move the `getLineItemType` method into a separate service because then it can be easily decorated (even multiple times) to add support for new types. This is not really possible as it is currently done as the method is called by the service itself, so it will not use the decorated service above it.

**Comment by schmitzcarsten** [comment]
I'm not sure why it should not be ready by now. Promotions have another lineType and are calculated for mollie.

Would you please explain what you are expecting that should not work by now?

**Comment by AndreasA** [comment]
Hi, I meant that if their are custom line item types used by custom extensions for the project or third-party plugins. 

Like e.g. the `swagBundle` that the https://docs.shopware.com/en/shopware-platform-dev-en/how-to/indepth-guide-bundle/checkout 
docs example mentions. 

This would currently result in those line item types being TYPE_DIGITAL
 which is not really correct. I guess it would still be TYPE_PHYSICAL in that case.

Also if the line item total is below zero you currently return promotion as line item which might not necessarily be the case but that is probably not that big an issue as it should be correct in most cases and will not hurt if it is returned as discount.

**Comment by schmitzcarsten** [comment]
I don't see a problem that the current implementation should not be functional in these cases. 
If you have an example hat leads to a problem, please let me know.

**Comment by AndreasA** [comment]
@schmitzcarsten It will probably still work but e.g. the bundle would be marked as a digital good order line item instead of physical.

Another example: A surcharges plugin that adds a surcharge if the customer orders too little. This would currently be marked as digital as well but it would actually be a `Surcharge` there is a type for t his in mollie.

Not strictly and issue but still an improvement if this could be done more dynamic which just requires a separate service because then it is easily decoratable with Symfony.
