### ISSUE TITLE
FlowBuilder Aware interfaces is overridden by interface classes in polyfill folder

### ISSUE THREAD

**Issue by huytdq94** [mollie/Shopware6#733]
Hello, 

I'm currently working on a project that uses store.shopware.com/molliepayments plugin (4.2.0).  I've encountered an issue with interface classes in `molliepayments/polyfill` folder. With these classes, Shopware will throw the exception if the `FEATURE_NEXT_17858` feature flag is inactive and makes FlowBuilder crash. You could check the `Shopware\Core\Framework\Event BusinessEventCollector` class line 80.
For example: the `Shopware\Core\Framework\Event\MailAware` was overridden by the `molliepayments/polyfill/Shopware/Core/Framework/Event/MailAware` interface, and that interface is not an instance of the BusinessEventInterface because its not extended the `MailActionInterface` anymore.

IMHO, these interfaces should be removed or only used for compatible Shopware versions.

Shopware version: 6.4.20.2
Mollie versions: 4.2.0

**Comment by BlackScorp** [comment]
Hi thanks for pointing it out, i will fix this after Shopware 6.6 update
