### ISSUE TITLE
Still getting a Cart validation error when creating an Apple Pay Direct order as guest user

### ISSUE THREAD

**Issue by leo-haerdle** [mollie/Shopware6#777]
Hi there,
We are experiencing a similar error like the one mentioned in [issue/574](https://github.com/mollie/Shopware6/issues/574).

This is supposed to be fixed, but our problem might be related.
As described in the original issue we are getting a very similar Error like this:
`
Apple Pay Direct error when finishing payment: The cart is invalid, got 1 error(s). salutation-missing-profile: A salutation needs to be defined for the customer profile SW77821, <user name>. {"error":"[object] (Shopware\\Core\\Checkout\\Cart\\Exception\\InvalidCartException(code: 0): The cart is invalid, got 1 error(s).\nsalutation-missing-profile: A salutation needs to be defined for the customer profile SW77821, <user name>. at /srv/www/htdocs/shop/vendor/shopware/core/Checkout/Cart/CartException.php:76)"} {"file":"/srv/www/htdocs/shop/custom/plugins/MolliePayments/src/Controller/Storefront/ApplePayDirect/ApplePayDirectControllerBase.php","line":416,"class":"Kiener\\MolliePayments\\Controller\\Storefront\\ApplePayDirect\\ApplePayDirectControllerBase","callType":"->","function":"finishPayment","url":"/mollie/apple-pay/start-payment","ip":"<ip>","http_method":"POST","server":"<url>","referrer":"<url>“}
`
When a guest user wants to use apple pay direct we get Warnings that there is an error (The payment with Apple Pay failed.) and a warning that The profile has no salutation. 

Until Version 4.6 there was a link to set the default salutation but the payment could not be finished anyway.
Since the new update 4.9.1 the link just goes to account / registering / login page.

We use Shopware 6.4.20.0
For over 2 months we are in contact with the support and we hoped for a solution with update 4.9.1.

I am not sure where the problem exactly lies, but the Error description and analysis in the original issue seems to be matching perfectly quite good with our problem.
Any Ideas if this is a new problem, or what could be done to fix it?
Best Regards,

Leo Härdle

**Comment by BlackScorp** [comment]
Apple Pay does not provide a salutation, therefore we are searching in shopware for a salutation with the technical name "not_specified" in shopware salutations, to set them. if you dont have a salutation with this technical name, then it will not work i think.

can you add a new salutation in shopware admin with technical name "not_specified"?

**Comment by leo-haerdle** [comment]
Hey thank you for the fast reply.
We have a salutation with the technical name "undefined" and the name "not specified" which is pobably exactly the one I need.
I changed the technical name to 'not_specified' but it does not help.
But unfortunately the problem remains exactly the same.

**Comment by leo-haerdle** [comment]
Hey again, 
Thanks for the answer ultimately it lead to success.
🥳. It works now.

**Comment by BlackScorp** [comment]
hi awesome, love such easy tasks :D then i can close the ticket
