### ISSUE TITLE
Subscriptions: Let customer choose the interval

### ISSUE THREAD

**Issue by Donderda** [mollie/Shopware6#793]
Hello,

It would be a great feature if the customer could define the intervals for their subscriptions, as this can be very individual...

Is such a feature planned or already in existence, and I just missed it?

**Comment by BlackScorp** [comment]
Hi, usually we create product variants with different subscription length the customer can then select the variant (like t-shirt sizes)

**Comment by Donderda** [comment]
Yes, but that’s not very customer friendly TBH. Some people might to have something all 2 weeks, others 5 days and other every 9 months. This way I would have to create gazillions of products just for one variant of a product :-/Am 25.07.2024 um 16:27 schrieb Vitalij Mik ***@***.***>:﻿
Hi, usually we create product variants with different subscription length the customer can then select the variant (like t-shirt sizes)

**Comment by BlackScorp** [comment]
You create one product and a property for subscription length, then you can autogenerate product variations based on that property. then you can go through each variant and enable subscription there and define the length.   

maybe i dont understand the usecase, can you elaborate it a little more?

**Comment by BlackScorp** [comment]
@Donderda iam going to close this ticket, let me know if i misunderstood the usecase

**Comment by Donderda** [comment]
Das ist ein Test :)
