### ISSUE TITLE
version v1.0.7 non-functional

### ISSUE THREAD

**Issue by darinda** [mollie/Shopware6#8]
the [require once statement](https://github.com/mollie/Shopware6/commit/c9253d97fd4ba41e93993933654739e06af72491#diff-602c0a06e1945a6277e64e990885fb60R5) introduced in v1.0.7 completely breaks the shopware 6 installation after updating the plugin to this version.

Autoloading should be done via composer, not via manually requiring autoload files.

Update: This is only true when installing the plugin via composer. It works when installed via shopware store & backend

**Comment by reindernl** [comment]
I got a request to implement it without the autoloading feature of composer. I found no issues with it, so I implemented it that way. I will check your findings and fix it where necessary. Thanks for your help.
