### ISSUE TITLE
Mollie Components x Shopware Storefront API

### ISSUE THREAD

**Issue by dartdevdave** [mollie/Shopware6#826]
I am using the mollie plugin for my shopware store. I don't want the users to get redirected to mollie when paying with a credit card. For that I use the mollie components for credit cards. I can generate a cardToken by the mollie components. Now how can I run a payment with the shopware storefront api and the cardToken? I have tried sending the cardToken in the handle-payment method of the storefront api but that won't work. Is there a solution with only using the storefront api and not using the admin api of shopware?

**Comment by BlackScorp** [comment]
hi yes, 

you have to call the method to store credit card token first, it will be saved in cusomters custom field, then you can handle the payment and the token will be transfered from the user to mollie api.

POST store-api/mollie/creditcard/store-token/{customerId}/{token}

hope that helps

**Comment by BlackScorp** [comment]
@dartdevdave hope this answer the question, iam going to close the ticket, feel free to reopen ist the question is not answered

**Comment by dartdevdave** [comment]
Thank you for your response, @BlackScorp.

I successfully managed to store the Mollie cardToken into the custom field of the customer using the request URL you provided. After that, I called the handle payment route of the Storefront API. However, I'm now encountering the error code: CHECKOUT__MOLLIE_COULD_NOT_CREATE_PAYMENT_URL.

To troubleshoot, I made a direct request to the Mollie API with the same cardToken, and the payment was successfully created. I am using "http://testing.mollie.shop/" as the host to avoid using "localhost" for the storefront URL.

Could you help me understand why I'm still receiving this error code when calling the Storefront API?

Thank you in advance!
