### ISSUE TITLE
Issue with Mollie Components During Re-Payment Process

### ISSUE THREAD

**Issue by dartdevdave** [mollie/Shopware6#839]
Hello,

I am currently utilizing the Mollie Components within my payment flow. The components function correctly for the initial payment of an order. However, I encounter an issue when a payment fails. In such cases, I use the orderSetPayment request via the storefront API, followed by the handlePaymentMethod to initiate the payment again.

At this point, I am redirected to Mollie's page to enter the credit card details. This redirection is contrary to my intention of using the Mollie Components, which are meant to eliminate such redirects.

Could you please clarify whether the Mollie Components are intended to support re-payments for an order, or if there are specific configurations required to enable this functionality?

Thank you for your assistance.

Best regards,

**Comment by Anju023** [comment]
maybe this will help
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
I put the necessary dlls in the archive

**Comment by BlackScorp** [comment]
Hi @dartdevdave 

if you have to re-enter the credit card details, this means either the credit card token was not stored or is removed at some point.

you only have to type in the credit card information if the customer does not have the credit card token in his custom fields.

can you check it out?

best regards

**Comment by dartdevdave** [comment]
I have thoroughly reviewed the payment flow and confirmed that the issue was due to the absence of a stored credit card for the customer. I am pleased to report that everything is functioning correctly now. Thank you very much for your assistance!
