### ISSUE TITLE
Error executing API call (422: Unprocessable Entity) when doing billie payments without a company name

### ISSUE THREAD

**Issue by harli91** [mollie/Shopware6#840]
When doing a billie payment without a company name I get the following errors

`Could not create a Mollie payment url due to the following error: [2024-09-20T09:07:34+0000] Error executing API call (422: Unprocessable Entity): A billing organization name is required for this payment method. Documentation: https://docs.mollie.com/reference/v2/orders-api/create-order-payment
`

**Comment by BlackScorp** [comment]
hi @harli91 thats correct, Billie is a B2B Payment method and does not work without company name. See here

https://docs.mollie.com/reference/extra-payment-parameters#billie

**Comment by harli91** [comment]
@BlackScorp shouldn't the payment method be hidden when a company name is not present?

**Comment by BlackScorp** [comment]
@harli91 usually for B2B you have a special saleschannel because the Taxes are also calculated differently, so the payment method should be assigend to the B2B saleschannel

**Comment by BlackScorp** [comment]
@harli91 in order to support the payment method rule, we hide the payment methods only in special cases.

1) we hide apple pay if it is not supported by the browser
2) we hide payment methods based on mollies limits, country and currency but only if you enable the config to hide them (some payment methods are working with a minimum or maximum cart limit or only within different countries and currencies)

you can create a custom rule and add this rule to the payment method to hide billie

**Comment by harli91** [comment]
@BlackScorp from what I can see in the documentation these parameters are "recommended" not required so why is the payment failing ?

**Comment by BlackScorp** [comment]
@harli91 it is recommend to have those values but the organisation Name in the billing address is required to have for billie

**Comment by BlackScorp** [comment]
@harli91 we are going to hide the payment method based on account type in the next release

**Comment by harli91** [comment]
@BlackScorp sweet, thanks :)

**Comment by harli91** [comment]
@BlackScorp I see you did a release 3 days ago, was the fix included? can't find it in the release notes

**Comment by BlackScorp** [comment]
@harli91 no, those were just hotfixes to fix ciritical issues

**Comment by harli91** [comment]
@BlackScorp do you know when will a the next release will happen, thanks?

**Comment by BlackScorp** [comment]
@harli91 planed for next week, as long as nothing comes in between

**Comment by BlackScorp** [comment]
fixed with #849
