### ISSUE TITLE
Task queued, but corresponding feature is disabled

### ISSUE THREAD

**Issue by carstenjaksch** [mollie/Shopware6#843]
The scheduled task `mollie.subscriptions.renewal_reminder` is queued, but the subscriptions feature is disabled.

I had the issue that the task was running but never finished. Had to manually trigger the task. All other tasks were skipped for half a month, until I recognized that.

<img width="986" alt="Bildschirm­foto 2024-09-25 um 08 36 24" src="https://github.com/user-attachments/assets/df41d2f6-fb3c-4cb8-8104-0f4b0938832f">
<img width="1276" alt="Bildschirm­foto 2024-09-25 um 08 36 02" src="https://github.com/user-attachments/assets/ab3b5ec1-d213-4359-91b1-df0b24dddb12">

**Comment by carstenjaksch** [comment]
I updated to version 4.10.1 and it seems the mentioned memory usage was causing the issue.

But the subscription task is still scheduled. Isn't it better to schedule the task only if the corresponding feature is enabled?

**Comment by BlackScorp** [comment]
@carstenjaksch i have to check if there is a way to remove tasks in shopware, but currently if the feature is disabled, this task does nothing right now

**Comment by BlackScorp** [comment]
@carstenjaksch https://developer.shopware.com/docs/guides/plugins/plugins/plugin-fundamentals/add-scheduled-task.html  it seems like i can only register scheduled tasks but i cannot remove them after wards, they are installed during plugin update
