### ISSUE TITLE
422: Unprocessable Entity: The 'lines' field is missing

### ISSUE THREAD

**Issue by jackyraimond** [mollie/Shopware6#862]
I want to make a partial refund by sending a JSON to  `/api/_action/mollie/refund` as mentioned in the [WIKI](https://github.com/mollie/Shopware6/wiki/Refunds). The JSON is like this:

```JSON
{
  "orderId" : "0191eb345e137363938387fa9d9916dc",
  "items" : [
    {
      "id": "018e68f3fb7c70e48754edb9a65c4ed9",
      "amount": 33.05,
      "quantity": 1,
      "resetStock": 0
    }
  ]
}
```

But I'm getting an error with this output:

```JSON
{
  "success": false,
  "errors": [
    "[2024-10-09T11:28:49+0000] Error executing API call (422: Unprocessable Entity): The 'lines' field is missing. Documentation: https:\/\/docs.mollie.com\/overview\/handling-errors. Field: lines"
  ]
}
```

If I remove the items sections, then it's working but then it will create a full refund.

**Comment by jackyraimond** [comment]
Thanks for the update. Maybe it's a good idea to update the documentation, because it was unclear to me I needed to lineItem ID instead of the product ID. Also I didn't know the full amount should be added when doing a partial refund.

**Comment by BlackScorp** [comment]
@jackyraimond thx for the info, 

i changed the value to "sw-order-item-id"
the amount was already in the example

https://github.com/mollie/Shopware6/wiki/Refunds#start-refund-refund-manager
