### ISSUE TITLE
Error when cancelling payment

### ISSUE THREAD

**Issue by alexbaat** [mollie/Shopware6#9]
When I cancel the payment on Mollie page I return to the shop with an error 500:

Illegal transition "cancel" from state "666eea644c1f4a02a4e53994f0601e7c". Possible transitions are: refund, refund_partially, reopen

Tested it with 1.0.7 on Shopware 6.1.5.

**Comment by sdobbelaere** [comment]
Same here:

Illegal transition "cancel" from state "4e67d261b50f41b3bcc6193957d88992". Possible transitions are: refund, refund_partially, reopen

![Screenshot 2020-04-13 at 10 10 16](https://user-images.githubusercontent.com/16462709/79104498-0364c900-7d6f-11ea-9cef-d98b86f4e8ac.png)

Tested with 1.0.7 on Shopware 6.1.5.

**Comment by reindernl** [comment]
Thanks for your help. I will use your findings for the next update of the plugin. In the previous versions of Shopware 6 there was no 'reopen' flow, therefor we had to cancel the order. This has changed in 6.1.5, so luckily we can build a better solution 😊
