### ISSUE TITLE
Error executing API call (404: Not Found): Order ord_1.o2io4c exists, but belongs to a different website profile than the API key used..

### ISSUE THREAD

**Issue by harli91** [mollie/Shopware6#900]
We recently get the following errors in our logs, can you explain why is this error occurring?

**Comment by BlackScorp** [comment]
hi @harli91 

when we create an Order at mollie, we recieve the mollie order id, this is then saved inside shopwares custom field. so then we can map the shopware order to mollie order.

in this case it seems like the order was created with an old api key.
then you changed the API key
and then you try to update the order where the new API Key is configured.

this ofc will not work. you need to edit an order with the original api key

**Comment by BlackScorp** [comment]
@harli91 iam going to close the ticket, feel free to reopen if there are further question or create a new ticket
