### ISSUE TITLE
Billie: A billing organization name is required

### ISSUE THREAD

**Issue by carstenjaksch** [mollie/Shopware6#904]
Hey, I found this issue: https://github.com/mollie/Shopware6/issues/840

However, the error is not solved. Steps to reproduce:

1. Set account to "business" type.
2. Order with address of "private" type.
3. You will be redirected to a page with 500 error.

Although the account type is set to business, Mollie takes the address company name for the API call.

In that case, Billie should not be displayed at all. We have a rule in Shopware that Billie should not be available to private customers. But this rule does not affect private addresses and there is no way to adjust that.

As you can see in the screenshot, we have no way to check if company name of the address is there or the address is a business one. So the Mollie plugin must ensure that Billie is not available unless a business address with company name is available.

Or at least don't throw a 500 error, implement an error message and let the customer choose another payment method or fix the address.

<img width="462" alt="Bildschirm­foto 2024-12-04 um 13 43 35" src="https://github.com/user-attachments/assets/f4cfc826-e477-41ab-8b7b-609b8e842b75">

Screenshot of log entry:

<img width="895" alt="Bildschirm­foto 2024-12-04 um 13 34 30" src="https://github.com/user-attachments/assets/b620683f-75ca-4ec3-8ed6-2e64c6d0407c">

Latest Mollie plugin version by the way.

**Comment by BlackScorp** [comment]
Hi thx for the ticket,

i forgot about the case that you can still create a private address even with business accounts. will fix it
