### ISSUE TITLE
Wrong sales channel used when changing payment status in admin

### ISSUE THREAD

**Issue by belendel** [mollie/Shopware6#98]
When changing the payment status in admin to refunded we get an error 500 with the following code message:

```javascript
{
  "errors": [
    {
      "code": "404",
      "status": "500",
      "title": "Internal Server Error",
      "detail": "[2021-04-09T12:10:44+0000] Error executing API call (404: Not Found): No order exists with token ord_1w38i2.. Documentation: https://docs.mollie.com/guides/handling-errors"
    }
  ]
}
```

It seems the PaymentStateSubscriber uses the MollieApiClient instead of MollieApiFactory. The results in the wrong API key being used.

**Comment by schmitzcarsten** [comment]
thx for reporting, we will have a check

**Comment by schmitzcarsten** [comment]
@belendel We will add this in the next release. The fix is commit 
https://github.com/mollie/Shopware6/commit/103d3c0d992ae5c45de7b394c43675ed9ae099c1
